//! Raw FFI bindings to a vendored, source-built libfreerdp3 / libwinpr3.
//!
//! Generated by `build.rs` (bindgen) against the headers FreeRDP installs at
//! build time — including the cmake-generated `settings_keys.h`, which is why
//! the bindings cannot live in-tree. Everything here is `unsafe` C surface;
//! the safe driver lives in `pier_core::remote_desktop::rdp_freerdp`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// RDPGFX dynamic virtual channel name — the channel whose connect event we
/// hook to wire the H.264/AVC444 graphics pipeline into the GDI surface.
/// Matches `RDPGFX_DVC_CHANNEL_NAME` in `freerdp/channels/rdpgfx.h`.
pub const RDPGFX_DVC_CHANNEL_NAME: &[u8] = b"Microsoft::Windows::RDS::Graphics\0";

// ── Short aliases ───────────────────────────────────────────────────────────
// bindgen namespaces C enum variants as `<EnumType>_<Variant>`. Re-export the
// handful we use under their bare C names so the driver reads like the C API.

// Settings keys (`freerdp/settings_keys.h`, generated at build time).
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_AutoLogonEnabled as FreeRDP_AutoLogonEnabled;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_DisableFullWindowDrag as FreeRDP_DisableFullWindowDrag;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_DisableMenuAnims as FreeRDP_DisableMenuAnims;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_DisableWallpaper as FreeRDP_DisableWallpaper;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_GfxAVC444 as FreeRDP_GfxAVC444;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_GfxAVC444v2 as FreeRDP_GfxAVC444v2;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_GfxH264 as FreeRDP_GfxH264;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_IgnoreCertificate as FreeRDP_IgnoreCertificate;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_NlaSecurity as FreeRDP_NlaSecurity;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_RdpSecurity as FreeRDP_RdpSecurity;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_RemoteFxCodec as FreeRDP_RemoteFxCodec;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_SoftwareGdi as FreeRDP_SoftwareGdi;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_SupportGraphicsPipeline as FreeRDP_SupportGraphicsPipeline;
pub use self::FreeRDP_Settings_Keys_Bool_FreeRDP_TlsSecurity as FreeRDP_TlsSecurity;
pub use self::FreeRDP_Settings_Keys_String_FreeRDP_Domain as FreeRDP_Domain;
pub use self::FreeRDP_Settings_Keys_String_FreeRDP_Password as FreeRDP_Password;
pub use self::FreeRDP_Settings_Keys_String_FreeRDP_ServerHostname as FreeRDP_ServerHostname;
pub use self::FreeRDP_Settings_Keys_String_FreeRDP_Username as FreeRDP_Username;
pub use self::FreeRDP_Settings_Keys_UInt32_FreeRDP_ColorDepth as FreeRDP_ColorDepth;
pub use self::FreeRDP_Settings_Keys_UInt32_FreeRDP_DesktopHeight as FreeRDP_DesktopHeight;
pub use self::FreeRDP_Settings_Keys_UInt32_FreeRDP_DesktopWidth as FreeRDP_DesktopWidth;
pub use self::FreeRDP_Settings_Keys_UInt32_FreeRDP_ServerPort as FreeRDP_ServerPort;

// Values folded out of function-like / multi-line C macros via `wrapper.h`.
pub use self::PierxConst_PIERX_KBDEXT as PIERX_KBDEXT;
pub use self::PierxConst_PIERX_PIXEL_FORMAT_RGBA32 as PIERX_PIXEL_FORMAT_RGBA32;
pub use self::PierxConst_PIERX_PIXEL_FORMAT_RGBX32 as PIERX_PIXEL_FORMAT_RGBX32;
