use std::borrow::Cow;

use gpui::{AssetSource, Result, SharedString};

static ASSETS: &[(&str, &[u8])] = &[
    (
        "icons/arrow-down.svg",
        include_bytes!("../assets/icons/arrow-down.svg"),
    ),
    (
        "icons/arrow-up.svg",
        include_bytes!("../assets/icons/arrow-up.svg"),
    ),
    (
        "icons/chart-pie.svg",
        include_bytes!("../assets/icons/chart-pie.svg"),
    ),
    (
        "icons/check.svg",
        include_bytes!("../assets/icons/check.svg"),
    ),
    (
        "icons/chevron-down.svg",
        include_bytes!("../assets/icons/chevron-down.svg"),
    ),
    (
        "icons/chevron-left.svg",
        include_bytes!("../assets/icons/chevron-left.svg"),
    ),
    (
        "icons/chevron-right.svg",
        include_bytes!("../assets/icons/chevron-right.svg"),
    ),
    (
        "icons/close.svg",
        include_bytes!("../assets/icons/close.svg"),
    ),
    (
        "icons/container.svg",
        include_bytes!("../assets/icons/container.svg"),
    ),
    (
        "icons/database.svg",
        include_bytes!("../assets/icons/database.svg"),
    ),
    (
        "icons/delete.svg",
        include_bytes!("../assets/icons/delete.svg"),
    ),
    (
        "icons/ellipsis.svg",
        include_bytes!("../assets/icons/ellipsis.svg"),
    ),
    (
        "icons/file-text.svg",
        include_bytes!("../assets/icons/file-text.svg"),
    ),
    ("icons/file.svg", include_bytes!("../assets/icons/file.svg")),
    (
        "icons/folder-plus.svg",
        include_bytes!("../assets/icons/folder-plus.svg"),
    ),
    (
        "icons/folder.svg",
        include_bytes!("../assets/icons/folder.svg"),
    ),
    (
        "icons/gallery-vertical-end.svg",
        include_bytes!("../assets/icons/gallery-vertical-end.svg"),
    ),
    (
        "icons/git-branch.svg",
        include_bytes!("../assets/icons/git-branch.svg"),
    ),
    (
        "icons/git-commit.svg",
        include_bytes!("../assets/icons/git-commit.svg"),
    ),
    (
        "icons/globe.svg",
        include_bytes!("../assets/icons/globe.svg"),
    ),
    (
        "icons/inbox.svg",
        include_bytes!("../assets/icons/inbox.svg"),
    ),
    (
        "icons/inspector.svg",
        include_bytes!("../assets/icons/inspector.svg"),
    ),
    (
        "icons/layout-dashboard.svg",
        include_bytes!("../assets/icons/layout-dashboard.svg"),
    ),
    (
        "icons/loader.svg",
        include_bytes!("../assets/icons/loader.svg"),
    ),
    ("icons/map.svg", include_bytes!("../assets/icons/map.svg")),
    ("icons/moon.svg", include_bytes!("../assets/icons/moon.svg")),
    (
        "icons/panel-left-close.svg",
        include_bytes!("../assets/icons/panel-left-close.svg"),
    ),
    (
        "icons/panel-left-open.svg",
        include_bytes!("../assets/icons/panel-left-open.svg"),
    ),
    (
        "icons/panel-right-close.svg",
        include_bytes!("../assets/icons/panel-right-close.svg"),
    ),
    (
        "icons/panel-right-open.svg",
        include_bytes!("../assets/icons/panel-right-open.svg"),
    ),
    ("icons/play.svg", include_bytes!("../assets/icons/play.svg")),
    ("icons/plus.svg", include_bytes!("../assets/icons/plus.svg")),
    (
        "icons/refresh-cw.svg",
        include_bytes!("../assets/icons/refresh-cw.svg"),
    ),
    (
        "icons/replace.svg",
        include_bytes!("../assets/icons/replace.svg"),
    ),
    (
        "icons/server.svg",
        include_bytes!("../assets/icons/server.svg"),
    ),
    (
        "icons/settings-2.svg",
        include_bytes!("../assets/icons/settings-2.svg"),
    ),
    (
        "icons/settings.svg",
        include_bytes!("../assets/icons/settings.svg"),
    ),
    (
        "icons/square-terminal.svg",
        include_bytes!("../assets/icons/square-terminal.svg"),
    ),
    (
        "icons/square.svg",
        include_bytes!("../assets/icons/square.svg"),
    ),
    ("icons/sun.svg", include_bytes!("../assets/icons/sun.svg")),
    (
        "icons/triangle-alert.svg",
        include_bytes!("../assets/icons/triangle-alert.svg"),
    ),
    // — Added for the Git graph/managers views —
    (
        "icons/search.svg",
        include_bytes!("../assets/icons/search.svg"),
    ),
    ("icons/user.svg", include_bytes!("../assets/icons/user.svg")),
    ("icons/copy.svg", include_bytes!("../assets/icons/copy.svg")),
    (
        "icons/calendar.svg",
        include_bytes!("../assets/icons/calendar.svg"),
    ),
    (
        "icons/external-link.svg",
        include_bytes!("../assets/icons/external-link.svg"),
    ),
    ("icons/undo.svg", include_bytes!("../assets/icons/undo.svg")),
    (
        "icons/circle-check.svg",
        include_bytes!("../assets/icons/circle-check.svg"),
    ),
    (
        "icons/folder-open.svg",
        include_bytes!("../assets/icons/folder-open.svg"),
    ),
    (
        "icons/ellipsis-vertical.svg",
        include_bytes!("../assets/icons/ellipsis-vertical.svg"),
    ),
    (
        "icons/github.svg",
        include_bytes!("../assets/icons/github.svg"),
    ),
    // — File-type icons for the file browser row —
    (
        "icons/book-open.svg",
        include_bytes!("../assets/icons/book-open.svg"),
    ),
    (
        "icons/palette.svg",
        include_bytes!("../assets/icons/palette.svg"),
    ),
    // — Phosphor-Icons additions (Pier parity) —
    // Added so Pier-X can render every SF Symbol Pier uses with a
    // cross-platform equivalent. See SKILL.md §icons + CLAUDE.md rules.
    (
        "icons/arrow-circle-down.svg",
        include_bytes!("../assets/icons/arrow-circle-down.svg"),
    ),
    (
        "icons/arrow-circle-down-fill.svg",
        include_bytes!("../assets/icons/arrow-circle-down-fill.svg"),
    ),
    (
        "icons/arrow-circle-left.svg",
        include_bytes!("../assets/icons/arrow-circle-left.svg"),
    ),
    (
        "icons/arrow-circle-right.svg",
        include_bytes!("../assets/icons/arrow-circle-right.svg"),
    ),
    (
        "icons/arrow-circle-right-fill.svg",
        include_bytes!("../assets/icons/arrow-circle-right-fill.svg"),
    ),
    (
        "icons/arrow-circle-up.svg",
        include_bytes!("../assets/icons/arrow-circle-up.svg"),
    ),
    (
        "icons/arrow-circle-up-fill.svg",
        include_bytes!("../assets/icons/arrow-circle-up-fill.svg"),
    ),
    (
        "icons/arrow-right.svg",
        include_bytes!("../assets/icons/arrow-right.svg"),
    ),
    (
        "icons/arrows-counter-clockwise.svg",
        include_bytes!("../assets/icons/arrows-counter-clockwise.svg"),
    ),
    (
        "icons/arrows-left-right.svg",
        include_bytes!("../assets/icons/arrows-left-right.svg"),
    ),
    (
        "icons/brackets-curly.svg",
        include_bytes!("../assets/icons/brackets-curly.svg"),
    ),
    (
        "icons/brain.svg",
        include_bytes!("../assets/icons/brain.svg"),
    ),
    (
        "icons/circle-check-fill.svg",
        include_bytes!("../assets/icons/circle-check-fill.svg"),
    ),
    (
        "icons/circle-user-fill.svg",
        include_bytes!("../assets/icons/circle-user-fill.svg"),
    ),
    (
        "icons/circle-x.svg",
        include_bytes!("../assets/icons/circle-x.svg"),
    ),
    (
        "icons/circle-x-fill.svg",
        include_bytes!("../assets/icons/circle-x-fill.svg"),
    ),
    (
        "icons/clock.svg",
        include_bytes!("../assets/icons/clock.svg"),
    ),
    (
        "icons/clock-counter-clockwise.svg",
        include_bytes!("../assets/icons/clock-counter-clockwise.svg"),
    ),
    (
        "icons/columns.svg",
        include_bytes!("../assets/icons/columns.svg"),
    ),
    (
        "icons/cylinder.svg",
        include_bytes!("../assets/icons/cylinder.svg"),
    ),
    (
        "icons/cylinder-fill.svg",
        include_bytes!("../assets/icons/cylinder-fill.svg"),
    ),
    (
        "icons/dots-three-circle.svg",
        include_bytes!("../assets/icons/dots-three-circle.svg"),
    ),
    (
        "icons/download-simple.svg",
        include_bytes!("../assets/icons/download-simple.svg"),
    ),
    (
        "icons/export.svg",
        include_bytes!("../assets/icons/export.svg"),
    ),
    (
        "icons/file-arrow-down.svg",
        include_bytes!("../assets/icons/file-arrow-down.svg"),
    ),
    (
        "icons/file-arrow-down-fill.svg",
        include_bytes!("../assets/icons/file-arrow-down-fill.svg"),
    ),
    (
        "icons/file-arrow-up.svg",
        include_bytes!("../assets/icons/file-arrow-up.svg"),
    ),
    (
        "icons/file-arrow-up-fill.svg",
        include_bytes!("../assets/icons/file-arrow-up-fill.svg"),
    ),
    (
        "icons/file-magnifying-glass.svg",
        include_bytes!("../assets/icons/file-magnifying-glass.svg"),
    ),
    (
        "icons/file-magnifying-glass-fill.svg",
        include_bytes!("../assets/icons/file-magnifying-glass-fill.svg"),
    ),
    (
        "icons/file-plus.svg",
        include_bytes!("../assets/icons/file-plus.svg"),
    ),
    (
        "icons/folder-fill.svg",
        include_bytes!("../assets/icons/folder-fill.svg"),
    ),
    (
        "icons/funnel.svg",
        include_bytes!("../assets/icons/funnel.svg"),
    ),
    (
        "icons/gear-fill.svg",
        include_bytes!("../assets/icons/gear-fill.svg"),
    ),
    (
        "icons/git-merge.svg",
        include_bytes!("../assets/icons/git-merge.svg"),
    ),
    (
        "icons/hard-drive.svg",
        include_bytes!("../assets/icons/hard-drive.svg"),
    ),
    (
        "icons/hard-drive-fill.svg",
        include_bytes!("../assets/icons/hard-drive-fill.svg"),
    ),
    (
        "icons/hash.svg",
        include_bytes!("../assets/icons/hash.svg"),
    ),
    (
        "icons/identification-card.svg",
        include_bytes!("../assets/icons/identification-card.svg"),
    ),
    (
        "icons/key.svg",
        include_bytes!("../assets/icons/key.svg"),
    ),
    (
        "icons/key-fill.svg",
        include_bytes!("../assets/icons/key-fill.svg"),
    ),
    (
        "icons/lightning.svg",
        include_bytes!("../assets/icons/lightning.svg"),
    ),
    (
        "icons/lightning-fill.svg",
        include_bytes!("../assets/icons/lightning-fill.svg"),
    ),
    (
        "icons/link.svg",
        include_bytes!("../assets/icons/link.svg"),
    ),
    (
        "icons/list-bullets.svg",
        include_bytes!("../assets/icons/list-bullets.svg"),
    ),
    (
        "icons/magnifying-glass-minus.svg",
        include_bytes!("../assets/icons/magnifying-glass-minus.svg"),
    ),
    (
        "icons/minus-circle.svg",
        include_bytes!("../assets/icons/minus-circle.svg"),
    ),
    (
        "icons/minus-circle-fill.svg",
        include_bytes!("../assets/icons/minus-circle-fill.svg"),
    ),
    (
        "icons/network.svg",
        include_bytes!("../assets/icons/network.svg"),
    ),
    (
        "icons/network-slash.svg",
        include_bytes!("../assets/icons/network-slash.svg"),
    ),
    (
        "icons/note-pencil.svg",
        include_bytes!("../assets/icons/note-pencil.svg"),
    ),
    (
        "icons/package-fill.svg",
        include_bytes!("../assets/icons/package-fill.svg"),
    ),
    (
        "icons/pencil-circle.svg",
        include_bytes!("../assets/icons/pencil-circle.svg"),
    ),
    (
        "icons/pencil-circle-fill.svg",
        include_bytes!("../assets/icons/pencil-circle-fill.svg"),
    ),
    (
        "icons/pencil-simple-line.svg",
        include_bytes!("../assets/icons/pencil-simple-line.svg"),
    ),
    (
        "icons/play-circle.svg",
        include_bytes!("../assets/icons/play-circle.svg"),
    ),
    (
        "icons/play-circle-fill.svg",
        include_bytes!("../assets/icons/play-circle-fill.svg"),
    ),
    (
        "icons/play-fill.svg",
        include_bytes!("../assets/icons/play-fill.svg"),
    ),
    (
        "icons/plus-circle.svg",
        include_bytes!("../assets/icons/plus-circle.svg"),
    ),
    (
        "icons/plus-circle-fill.svg",
        include_bytes!("../assets/icons/plus-circle-fill.svg"),
    ),
    (
        "icons/shield-check.svg",
        include_bytes!("../assets/icons/shield-check.svg"),
    ),
    (
        "icons/shield-check-fill.svg",
        include_bytes!("../assets/icons/shield-check-fill.svg"),
    ),
    (
        "icons/stack.svg",
        include_bytes!("../assets/icons/stack.svg"),
    ),
    (
        "icons/stack-fill.svg",
        include_bytes!("../assets/icons/stack-fill.svg"),
    ),
    (
        "icons/stop-circle-fill.svg",
        include_bytes!("../assets/icons/stop-circle-fill.svg"),
    ),
    (
        "icons/stop-fill.svg",
        include_bytes!("../assets/icons/stop-fill.svg"),
    ),
    (
        "icons/table.svg",
        include_bytes!("../assets/icons/table.svg"),
    ),
    (
        "icons/tag.svg",
        include_bytes!("../assets/icons/tag.svg"),
    ),
    (
        "icons/tag-fill.svg",
        include_bytes!("../assets/icons/tag-fill.svg"),
    ),
    (
        "icons/terminal.svg",
        include_bytes!("../assets/icons/terminal.svg"),
    ),
    (
        "icons/tray-fill.svg",
        include_bytes!("../assets/icons/tray-fill.svg"),
    ),
    (
        "icons/tree-structure.svg",
        include_bytes!("../assets/icons/tree-structure.svg"),
    ),
    (
        "icons/user-fill.svg",
        include_bytes!("../assets/icons/user-fill.svg"),
    ),
    (
        "icons/warning-fill.svg",
        include_bytes!("../assets/icons/warning-fill.svg"),
    ),
    (
        "icons/wifi.svg",
        include_bytes!("../assets/icons/wifi.svg"),
    ),
    (
        "icons/wifi-slash.svg",
        include_bytes!("../assets/icons/wifi-slash.svg"),
    ),
];

#[derive(Clone, Copy, Default)]
pub struct AppAssets;

impl AssetSource for AppAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(ASSETS
            .iter()
            .find(|(asset_path, _)| *asset_path == path)
            .map(|(_, bytes)| Cow::Borrowed(*bytes)))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        let prefix = path.trim_matches('/');
        let prefix = if prefix.is_empty() {
            String::new()
        } else {
            format!("{prefix}/")
        };

        Ok(ASSETS
            .iter()
            .filter_map(|(asset_path, _)| {
                if prefix.is_empty() || asset_path.starts_with(&prefix) {
                    Some((*asset_path).into())
                } else {
                    None
                }
            })
            .collect())
    }
}
