//! Compose → Kubernetes manifest converter.
//!
//! Targets the small subset of Compose features actually used by
//! Pier-X's built-in templates:
//!
//!   * services with `image` / `command` / `restart` / `environment`
//!     / `ports` / `volumes` / `depends_on`
//!   * top-level named volumes (`volumes:` section) — emitted as
//!     PersistentVolumeClaim manifests
//!
//! For each compose service we emit:
//!
//!   * a `Deployment` (1 replica, recreate strategy by default)
//!   * a `Service` of type `ClusterIP` for any service that exposes
//!     ports (mapped 1:1 from the compose `ports:` host:container
//!     pairs — only the *container* port lands in the Service spec
//!     because Kubernetes services don't carry a "host port" concept;
//!     a NodePort/LoadBalancer would still bind whatever the cluster
//!     decides). Port name = `tcp-<n>`.
//!
//! Bind mounts (`./www:/foo`) are dropped with a comment line — the
//! caller is supposed to translate these to ConfigMaps / hostPath
//! volumes case-by-case. Named volumes survive as a PVC + the same
//! name in the Pod's `volumes:` array.
//!
//! ## What this is NOT
//!
//! Not a full kompose replacement. We deliberately stop at the
//! shape that covers the templates we ship; if a user wants a
//! conversion of a hand-rolled compose with healthchecks / capability
//! drops / sysctls / network specs / secrets, they should run
//! `kompose convert` themselves. The dialog tells them so.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Bag of optional toggles that customise the conversion.
/// Historically named `IngressOptions`; kept as the same struct
/// for migration ease. Contains both Ingress generation knobs and
/// behaviour switches like the bind-mount → ConfigMap lift.
#[derive(Debug, Clone, Default)]
pub struct IngressOptions {
    /// Hostname used for the rule (`Host:` header match). Empty
    /// disables Ingress generation.
    pub host: String,
    /// Optional `ingressClassName` (Kubernetes ≥1.18). Most
    /// clusters need this set explicitly — common values are
    /// `nginx`, `traefik`, `alb`. Empty omits the field.
    pub ingress_class: String,
    /// Optional TLS secret name. When set, a `tls:` block is
    /// emitted referencing this secret for the configured host.
    pub tls_secret: String,
    /// Lift Compose bind mounts (`./local:/in/container[:ro]`)
    /// into Kubernetes `ConfigMap` resources. When true:
    ///
    ///   * One ConfigMap per `(service, source-dir)` pair, named
    ///     `<service>-<sanitised-source>`, with one placeholder
    ///     `README.md` entry that explains how to populate it.
    ///   * The Pod's `volumeMounts:` references the ConfigMap
    ///     instead of being dropped as an unsupported feature.
    ///
    /// Off (the default) keeps the legacy behaviour: bind mounts
    /// are dropped with a `# NOTE:` comment so the user knows to
    /// translate them by hand.
    pub lift_bind_mounts: bool,
}

/// Public entry point. Parses `yaml` as a Compose document and
/// serialises a multi-doc Kubernetes manifest (Deployment +
/// Service + PVC + optional Ingress sections separated by `---`).
///
/// `namespace` is woven into every manifest's metadata when set;
/// callers pass `None` to omit the namespace field (manifests then
/// apply to whatever the user's `kubectl` context defaults to).
///
/// Returns `Err(_)` only when the input fails to parse as YAML — a
/// well-formed-but-empty Compose document yields an empty string,
/// which the frontend renders as "no services to convert".
pub fn convert(yaml: &str, namespace: Option<&str>) -> Result<String, String> {
    convert_with_options(yaml, namespace, &IngressOptions::default())
}

/// Same as [`convert`] but additionally honours the supplied
/// `IngressOptions`. The two-function shape keeps the simple
/// "just convert to K8s" path easy at the call site while still
/// letting the panel pass through ingress configuration.
pub fn convert_with_options(
    yaml: &str,
    namespace: Option<&str>,
    ingress: &IngressOptions,
) -> Result<String, String> {
    let compose: ComposeFile = serde_yml::from_str(yaml)
        .map_err(|e| format!("compose YAML parse failed: {e}"))?;
    let ns = namespace
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    let mut docs: Vec<String> = Vec::new();
    let banner = match &ns {
        Some(n) => format!(
            "# Generated by Pier-X — Compose → Kubernetes (namespace: {n}).\n\
             # Bind mounts and unsupported Compose features are flagged inline.\n\
             # Run `kompose convert` for a higher-fidelity conversion.\n"
        ),
        None => "# Generated by Pier-X — Compose → Kubernetes.\n\
                 # Bind mounts and unsupported Compose features are flagged inline.\n\
                 # Run `kompose convert` for a higher-fidelity conversion.\n"
            .to_string(),
    };
    docs.push(banner);

    // Order services + volumes alphabetically so the output is
    // stable across runs — useful for diffing in version control.
    let mut service_keys: Vec<&String> = compose.services.keys().collect();
    service_keys.sort();
    let mut volume_keys: Vec<&String> = compose.volumes.keys().collect();
    volume_keys.sort();

    for vol in &volume_keys {
        let yaml = render_pvc(vol, ns.as_deref());
        docs.push(yaml);
    }

    // Collect HTTP-eligible (service_name, port) pairs and any
    // ConfigMap stubs lifted from bind mounts as we render each
    // service. ConfigMaps are emitted up-front so a `kubectl apply`
    // creates them before the Pod that references them.
    let mut http_routes: Vec<(String, u16)> = Vec::new();
    let mut configmap_stubs: Vec<ConfigMapStub> = Vec::new();
    let mut deployment_docs: Vec<String> = Vec::new();
    let mut service_docs: Vec<String> = Vec::new();

    for name in &service_keys {
        let svc = &compose.services[*name];
        let (dep_yaml, lifted) =
            render_deployment(name, svc, ns.as_deref(), ingress, &compose)?;
        deployment_docs.push(dep_yaml);
        for stub in lifted {
            configmap_stubs.push(stub);
        }
        if has_published_ports(svc) {
            service_docs.push(render_service(name, svc, ns.as_deref()));
            if let Some(port) = first_http_port(svc) {
                http_routes.push((name.to_string(), port));
            }
        }
    }

    // Top-level secrets / configs become Secret / ConfigMap stubs
    // emitted up-front so kubectl apply orders them before the
    // referencing Pod. Sorted alphabetically for stable diffs.
    let mut secret_keys: Vec<&String> = compose.secrets.keys().collect();
    secret_keys.sort();
    for k in &secret_keys {
        docs.push(render_secret_stub(k, &compose.secrets[*k], ns.as_deref()));
    }
    let mut config_keys: Vec<&String> = compose.configs.keys().collect();
    config_keys.sort();
    for k in &config_keys {
        docs.push(render_top_level_configmap(
            k,
            &compose.configs[*k],
            ns.as_deref(),
        ));
    }

    let mut network_keys: Vec<&String> = compose.networks.keys().collect();
    network_keys.sort();
    for k in &network_keys {
        docs.push(render_network_policy(k, ns.as_deref()));
    }

    for stub in &configmap_stubs {
        docs.push(render_configmap_stub(stub, ns.as_deref()));
    }
    docs.extend(deployment_docs);
    docs.extend(service_docs);

    if !ingress.host.trim().is_empty() && !http_routes.is_empty() {
        docs.push(render_ingress(&http_routes, ns.as_deref(), ingress));
    }

    Ok(docs.join("\n---\n"))
}

/// One ConfigMap to emit for a lifted bind mount. The render layer
/// fills in a placeholder `README.md` entry so the manifest is
/// kubectl-applyable as-is — users are expected to populate the
/// real keys/values via `kubectl create configmap --from-file=`
/// or by hand-editing the manifest before apply.
#[derive(Debug, Clone)]
struct ConfigMapStub {
    /// Final ConfigMap metadata.name.
    name: String,
    /// Original Compose `./<source>` token for the human-readable
    /// hint in the placeholder file.
    source: String,
    /// Compose-side mount path (`/usr/share/nginx/html`) — same
    /// purpose as `source`: a hint, not actually rendered into
    /// the ConfigMap data.
    mount_path: String,
    /// Service that requested this lift. Lets future "apply order"
    /// helpers cross-reference Pod ↔ ConfigMap pairs without
    /// re-parsing the whole manifest.
    #[allow(dead_code)]
    owner_service: String,
}

// ── Compose AST (subset) ────────────────────────────────────────

#[derive(Debug, Default, Deserialize)]
struct ComposeFile {
    #[serde(default)]
    services: BTreeMap<String, ComposeService>,
    #[serde(default)]
    volumes: BTreeMap<String, serde_yml::Value>,
    /// Top-level `secrets:` block. Each value is either a
    /// `{ file: path }` / `{ external: true }` / `{ environment: VAR }`
    /// shape; we honour `file:` (emits a Secret stub) and warn on
    /// the others.
    #[serde(default)]
    secrets: BTreeMap<String, serde_yml::Value>,
    /// Top-level `configs:` block. Same shape grammar as secrets;
    /// emits a ConfigMap stub for `file:` form, warns on others.
    #[serde(default)]
    configs: BTreeMap<String, serde_yml::Value>,
    /// Top-level `networks:` block. Each entry becomes a placeholder
    /// `NetworkPolicy` that allows traffic between pods labelled
    /// with the same network name — the closest analogue to
    /// Compose's "this network groups N services that can talk to
    /// each other".
    #[serde(default)]
    networks: BTreeMap<String, serde_yml::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct ComposeService {
    #[serde(default)]
    image: String,
    #[serde(default)]
    command: Option<serde_yml::Value>,
    #[serde(default)]
    restart: Option<String>,
    #[serde(default)]
    environment: Option<serde_yml::Value>,
    #[serde(default)]
    ports: Vec<serde_yml::Value>,
    #[serde(default)]
    volumes: Vec<serde_yml::Value>,
    #[serde(default)]
    depends_on: Option<serde_yml::Value>,
    /// Service-level `secrets:` references. Each entry is either
    /// a bare name (`- db_password`) or the long form with
    /// `source` / `target` / `mode`. Resolved against the
    /// top-level `secrets:` block.
    #[serde(default)]
    secrets: Vec<serde_yml::Value>,
    /// Service-level `configs:` references — same grammar as
    /// `secrets:`, resolved against top-level `configs:`.
    #[serde(default)]
    configs: Vec<serde_yml::Value>,
    /// Service-level `networks:` membership. Either an array of
    /// names (`- backend`) or a mapping (`backend: {}`). We
    /// ignore long-form details — only the membership names are
    /// used to label the Pod for NetworkPolicy selection.
    #[serde(default)]
    networks: Option<serde_yml::Value>,
    /// Compose `deploy:` block — only `replicas:` is honoured.
    /// Other fields (resources, restart_policy, placement, …)
    /// either don't translate cleanly or already have direct
    /// equivalents elsewhere in the manifest.
    #[serde(default)]
    deploy: Option<ComposeDeploy>,
    /// Service-level `healthcheck:` block. Maps to a Kubernetes
    /// liveness probe via `render_liveness_probe`.
    #[serde(default)]
    healthcheck: Option<ComposeHealthcheck>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
struct ComposeDeploy {
    /// Number of replicas to run. Maps directly to
    /// `Deployment.spec.replicas`. `0` is treated as "default
    /// (1)" so a hand-edited `replicas: 0` doesn't accidentally
    /// produce an unscheduled stack.
    #[serde(default)]
    replicas: Option<u32>,
    /// Compose `deploy.restart_policy.condition` mirrors the
    /// service-level `restart:` field but lives under `deploy:`.
    /// We honour both, with `deploy.restart_policy.condition`
    /// winning when set (Compose's documented precedence).
    #[serde(default)]
    restart_policy: Option<ComposeRestartPolicy>,
    /// Compose `deploy.resources.{limits,reservations}` — the
    /// closest analog to K8s `resources.{limits,requests}`. We
    /// translate `limits` → `resources.limits`, `reservations`
    /// → `resources.requests`. Compose units (`cpus: '0.5'`,
    /// `memory: '256M'`) are passed through verbatim — both
    /// platforms accept the same string forms.
    #[serde(default)]
    resources: Option<ComposeResources>,
    /// Compose `healthcheck` block — translated to a K8s
    /// `livenessProbe`. The shape mirrors the Compose spec:
    ///
    /// ```yaml
    /// healthcheck:
    ///   test: ["CMD", "curl", "-f", "http://localhost:80"]
    ///   interval: 30s
    ///   timeout: 5s
    ///   retries: 3
    ///   start_period: 5s
    /// ```
    ///
    /// `test:` is the only required field for translation; the
    /// rest map directly onto K8s probe knobs (interval →
    /// `periodSeconds`, retries → `failureThreshold`, etc.).
    #[serde(default)]
    healthcheck: Option<ComposeHealthcheck>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
struct ComposeResources {
    /// Hard limits (Compose's `deploy.resources.limits`). Maps
    /// to K8s `resources.limits`.
    #[serde(default)]
    limits: Option<ComposeResourceBucket>,
    /// Soft reservations (Compose's `deploy.resources.reservations`).
    /// Maps to K8s `resources.requests`.
    #[serde(default)]
    reservations: Option<ComposeResourceBucket>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
struct ComposeResourceBucket {
    /// CPU as a fractional core count (`'0.5'`, `'1.0'`).
    /// Stringified so YAML preserves the leading zero / decimal.
    #[serde(default)]
    cpus: Option<serde_yml::Value>,
    /// Memory string (`'256M'`, `'1G'`, `'512Mi'`). Compose and
    /// K8s share the same suffix grammar; we copy verbatim.
    #[serde(default)]
    memory: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
struct ComposeRestartPolicy {
    /// `none` / `on-failure` / `any`. Maps onto the same K8s
    /// `restartPolicy` enum the service-level `restart:` field
    /// already targets:
    ///   * `none` → `Never`
    ///   * `on-failure` → `OnFailure`
    ///   * `any` (default) → `Always` (omitted, K8s default)
    #[serde(default)]
    condition: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
struct ComposeHealthcheck {
    /// Either a `["CMD", argv...]` / `["CMD-SHELL", script]` array,
    /// the literal `["NONE"]`, or a bare string treated as
    /// `["CMD-SHELL", string]`.
    #[serde(default)]
    test: Option<serde_yml::Value>,
    /// Compose duration string ("30s", "1m30s"). Maps to
    /// `livenessProbe.periodSeconds` after parsing.
    #[serde(default)]
    interval: Option<String>,
    /// Per-attempt timeout, e.g. "5s". Maps to `timeoutSeconds`.
    #[serde(default)]
    timeout: Option<String>,
    /// Consecutive failures before declaring unhealthy. Maps to
    /// `failureThreshold`.
    #[serde(default)]
    retries: Option<u32>,
    /// Grace period at startup. Maps to `initialDelaySeconds`.
    #[serde(default)]
    start_period: Option<String>,
    /// Compose-only escape hatch. When `true` the healthcheck is
    /// considered disabled, no probe is emitted.
    #[serde(default)]
    disable: Option<bool>,
}

// ── Renderers ───────────────────────────────────────────────────

fn render_pvc(name: &str, namespace: Option<&str>) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    format!(
        "apiVersion: v1\n\
         kind: PersistentVolumeClaim\n\
         metadata:\n\
         {ns}\
         \x20\x20name: {name}\n\
         spec:\n\
         \x20\x20accessModes:\n\
         \x20\x20\x20\x20- ReadWriteOnce\n\
         \x20\x20resources:\n\
         \x20\x20\x20\x20requests:\n\
         \x20\x20\x20\x20\x20\x20storage: 1Gi\n",
        ns = ns_line,
        name = name,
    )
}

fn render_deployment(
    name: &str,
    svc: &ComposeService,
    namespace: Option<&str>,
    opts: &IngressOptions,
    compose: &ComposeFile,
) -> Result<(String, Vec<ConfigMapStub>), String> {
    if svc.image.trim().is_empty() {
        return Err(format!(
            "service '{name}' has no `image:` — only image-backed services are supported"
        ));
    }

    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };

    let mut s = String::new();
    // Service-level network memberships → Pod labels. The
    // top-level networks block emits a NetworkPolicy per entry
    // that selects on these same labels, so adding them here
    // wires the service into the right "VLAN" without the user
    // having to touch the manifest. Filtered to only networks
    // declared at the top level so a typo doesn't silently
    // bind to nothing.
    let net_memberships: Vec<String> =
        parse_service_networks(&svc.networks, &compose.networks);

    s.push_str("apiVersion: apps/v1\n");
    s.push_str("kind: Deployment\n");
    s.push_str("metadata:\n");
    s.push_str(&ns_line);
    s.push_str(&format!("  name: {name}\n"));
    s.push_str("  labels:\n");
    s.push_str(&format!("    app: {name}\n"));
    s.push_str("spec:\n");
    let replicas = svc
        .deploy
        .as_ref()
        .and_then(|d| d.replicas)
        .filter(|n| *n > 0)
        .unwrap_or(1);
    s.push_str(&format!("  replicas: {replicas}\n"));
    s.push_str("  strategy:\n");
    s.push_str("    type: Recreate\n");
    s.push_str("  selector:\n");
    s.push_str("    matchLabels:\n");
    s.push_str(&format!("      app: {name}\n"));
    s.push_str("  template:\n");
    s.push_str("    metadata:\n");
    s.push_str("      labels:\n");
    s.push_str(&format!("        app: {name}\n"));
    for net in &net_memberships {
        s.push_str(&format!(
            "        pier-x.network/{net}: \"in\"\n"
        ));
    }
    s.push_str("    spec:\n");

    // restartPolicy mapping. Compose has TWO sources for this:
    //   * `restart:` at the service level (legacy; values:
    //     `no` / `always` / `on-failure` / `unless-stopped`)
    //   * `deploy.restart_policy.condition:` (newer Swarm-mode
    //     spec; values: `none` / `on-failure` / `any`)
    // Per the Compose spec `deploy.restart_policy` wins when
    // both are set. Mapping → K8s:
    //   * `no` / `none` / `false` → Never
    //   * `on-failure` → OnFailure
    //   * everything else → omit (Always is K8s default)
    let restart_value = svc
        .deploy
        .as_ref()
        .and_then(|d| d.restart_policy.as_ref())
        .and_then(|rp| rp.condition.as_deref())
        .or(svc.restart.as_deref());
    if let Some(restart) = restart_value {
        let rp = match restart.trim() {
            "no" | "false" | "none" => Some("Never"),
            "on-failure" => Some("OnFailure"),
            _ => None,
        };
        if let Some(rp) = rp {
            s.push_str(&format!("      restartPolicy: {rp}\n"));
        }
    }

    s.push_str("      containers:\n");
    s.push_str(&format!("        - name: {name}\n"));
    s.push_str(&format!("          image: {}\n", svc.image));

    if let Some(cmd) = &svc.command {
        let parts = command_to_array(cmd);
        if !parts.is_empty() {
            s.push_str("          command:\n");
            for p in parts {
                s.push_str(&format!("            - {}\n", yaml_quote(&p)));
            }
        }
    }

    let env_pairs = parse_environment(&svc.environment);
    if !env_pairs.is_empty() {
        s.push_str("          env:\n");
        for (k, v) in env_pairs {
            s.push_str(&format!("            - name: {}\n", k));
            s.push_str(&format!("              value: {}\n", yaml_quote(&v)));
        }
    }

    let ports = parse_ports(&svc.ports);
    if !ports.is_empty() {
        s.push_str("          ports:\n");
        for p in &ports {
            s.push_str(&format!("            - containerPort: {}\n", p.container));
            s.push_str(&format!("              name: tcp-{}\n", p.container));
        }
    }

    if let Some(probe) = render_liveness_probe(svc.healthcheck.as_ref()) {
        s.push_str(&probe);
    }

    if let Some(resources) = render_resources(
        svc.deploy.as_ref().and_then(|d| d.resources.as_ref()),
    ) {
        s.push_str(&resources);
    }

    let parsed = parse_volumes(&svc.volumes);
    let mut lifted_stubs: Vec<ConfigMapStub> = Vec::new();
    let mut lifted_mounts: Vec<(String, String, bool)> = Vec::new(); // (cm_name, mount_path, read_only)
    if opts.lift_bind_mounts {
        for bm in &parsed.bind_mounts {
            let cm_name = bind_mount_configmap_name(name, &bm.source);
            lifted_mounts.push((cm_name.clone(), bm.mount_path.clone(), bm.read_only));
            lifted_stubs.push(ConfigMapStub {
                name: cm_name,
                source: bm.source.clone(),
                mount_path: bm.mount_path.clone(),
                owner_service: name.to_string(),
            });
        }
    }

    // Service-level secrets: map each reference to a Pod volume
    // backed by `secret: { secretName: <id> }` and a mount under
    // `/run/secrets/<target>` (the Compose convention). Long-form
    // entries with `target:` honour their custom path.
    let secret_refs: Vec<MountRef> =
        parse_mount_refs(&svc.secrets, MountRefKind::Secret, &compose.secrets);
    let config_refs: Vec<MountRef> =
        parse_mount_refs(&svc.configs, MountRefKind::Config, &compose.configs);

    let any_volume_mounts = !parsed.named_mounts.is_empty()
        || !lifted_mounts.is_empty()
        || !secret_refs.is_empty()
        || !config_refs.is_empty();
    if any_volume_mounts {
        s.push_str("          volumeMounts:\n");
        for vm in &parsed.named_mounts {
            s.push_str(&format!("            - name: {}\n", vm.volume));
            s.push_str(&format!("              mountPath: {}\n", vm.mount_path));
            if vm.read_only {
                s.push_str("              readOnly: true\n");
            }
        }
        for (cm_name, mount_path, read_only) in &lifted_mounts {
            s.push_str(&format!("            - name: {}\n", cm_name));
            s.push_str(&format!("              mountPath: {}\n", mount_path));
            if *read_only {
                s.push_str("              readOnly: true\n");
            }
        }
        for r in secret_refs.iter().chain(config_refs.iter()) {
            s.push_str(&format!("            - name: {}\n", r.volume_name()));
            s.push_str(&format!(
                "              mountPath: {}\n",
                r.mount_path()
            ));
            // Secrets are read-only by convention; configs follow
            // the same heuristic since Compose never makes them
            // writable either.
            s.push_str("              readOnly: true\n");
        }
    }

    if any_volume_mounts {
        s.push_str("      volumes:\n");
        let mut seen = std::collections::HashSet::new();
        for vm in &parsed.named_mounts {
            if seen.insert(vm.volume.clone()) {
                s.push_str(&format!("        - name: {}\n", vm.volume));
                s.push_str("          persistentVolumeClaim:\n");
                s.push_str(&format!("            claimName: {}\n", vm.volume));
            }
        }
        for (cm_name, _, _) in &lifted_mounts {
            if seen.insert(cm_name.clone()) {
                s.push_str(&format!("        - name: {}\n", cm_name));
                s.push_str("          configMap:\n");
                s.push_str(&format!("            name: {}\n", cm_name));
            }
        }
        for r in &secret_refs {
            if seen.insert(r.volume_name()) {
                s.push_str(&format!("        - name: {}\n", r.volume_name()));
                s.push_str("          secret:\n");
                s.push_str(&format!("            secretName: {}\n", r.id));
            }
        }
        for r in &config_refs {
            if seen.insert(r.volume_name()) {
                s.push_str(&format!("        - name: {}\n", r.volume_name()));
                s.push_str("          configMap:\n");
                s.push_str(&format!("            name: {}\n", r.id));
            }
        }
    }

    if !opts.lift_bind_mounts {
        for warn in &parsed.warnings {
            s.push_str(&format!(
                "      # NOTE: bind mount '{warn}' was dropped — translate to a hostPath\n      #       volume or a ConfigMap before applying.\n"
            ));
        }
    } else if !parsed.bind_mounts.is_empty() {
        s.push_str(
            "      # NOTE: bind mounts were lifted into placeholder ConfigMaps.\n\
             \x20\x20\x20\x20\x20\x20#       Populate them with the real file content before apply,\n\
             \x20\x20\x20\x20\x20\x20#       e.g. `kubectl create configmap NAME --from-file=DIR`.\n",
        );
    }

    if svc.depends_on.is_some() {
        s.push_str(
            "      # NOTE: Compose `depends_on` does not translate to Kubernetes —\n\
             \x20\x20\x20\x20\x20\x20#       use init containers, readiness probes, or a service mesh.\n",
        );
    }

    Ok((s, lifted_stubs))
}

/// Sanitise a Compose source path into a Kubernetes-safe name.
/// `<service>-<source>` lower-cased, with non-DNS-label chars
/// collapsed to `-`. K8s requires names to match `[a-z0-9]([-a-z0-9]*[a-z0-9])?`.
fn bind_mount_configmap_name(service: &str, source: &str) -> String {
    let stripped = source
        .trim_start_matches("./")
        .trim_start_matches('/')
        .trim_end_matches('/');
    let combined = format!("{service}-{stripped}");
    let mut out = String::with_capacity(combined.len());
    let mut last_dash = false;
    for ch in combined.chars() {
        let c = ch.to_ascii_lowercase();
        if c.is_ascii_alphanumeric() {
            out.push(c);
            last_dash = false;
        } else if !last_dash && !out.is_empty() {
            out.push('-');
            last_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    if out.is_empty() {
        "pierx-cm".to_string()
    } else {
        out
    }
}

/// Translate `deploy.resources` into a K8s `resources:` block on
/// the container. Returns `None` when neither limits nor
/// reservations have any populated field — emitting an empty
/// `resources: {}` block is valid YAML but adds clutter.
///
/// Compose `deploy.resources.limits.{cpus,memory}` →
/// `resources.limits.{cpu,memory}`. `reservations` →
/// `resources.requests`. Field names re-spelled (`cpus` → `cpu`)
/// because Compose and K8s differ on the singular form.
fn render_resources(resources: Option<&ComposeResources>) -> Option<String> {
    let r = resources?;
    let limits_cpu = r.limits.as_ref().and_then(|b| compose_cpu_string(b));
    let limits_mem = r.limits.as_ref().and_then(|b| b.memory.clone());
    let req_cpu = r.reservations.as_ref().and_then(|b| compose_cpu_string(b));
    let req_mem = r.reservations.as_ref().and_then(|b| b.memory.clone());

    if limits_cpu.is_none() && limits_mem.is_none() && req_cpu.is_none() && req_mem.is_none() {
        return None;
    }

    let mut s = String::new();
    s.push_str("          resources:\n");
    let has_limits = limits_cpu.is_some() || limits_mem.is_some();
    let has_requests = req_cpu.is_some() || req_mem.is_some();
    if has_limits {
        s.push_str("            limits:\n");
        if let Some(c) = &limits_cpu {
            s.push_str(&format!("              cpu: {}\n", yaml_quote(c)));
        }
        if let Some(m) = &limits_mem {
            s.push_str(&format!("              memory: {}\n", yaml_quote(m)));
        }
    }
    if has_requests {
        s.push_str("            requests:\n");
        if let Some(c) = &req_cpu {
            s.push_str(&format!("              cpu: {}\n", yaml_quote(c)));
        }
        if let Some(m) = &req_mem {
            s.push_str(&format!("              memory: {}\n", yaml_quote(m)));
        }
    }
    Some(s)
}

/// Pull `cpus:` out of a Compose resource bucket as a string.
/// Compose users sometimes write `cpus: 0.5` (number) and
/// sometimes `cpus: '0.5'` (string); both forms are sane and
/// K8s accepts the string form, so we coerce.
fn compose_cpu_string(bucket: &ComposeResourceBucket) -> Option<String> {
    match bucket.cpus.as_ref()? {
        serde_yml::Value::String(s) => Some(s.clone()),
        serde_yml::Value::Number(n) => Some(n.to_string()),
        _ => None,
    }
}

/// Translate a Compose `healthcheck` into a Kubernetes
/// `livenessProbe:` block. Returns `None` when:
///
///   * no healthcheck was declared, OR
///   * the healthcheck explicitly opted out
///     (`disable: true` / `test: ["NONE"]`), OR
///   * the `test:` shape is unrecognisable — we'd rather skip the
///     probe than emit a manifest that won't apply.
///
/// We only emit `livenessProbe` (not `readinessProbe`). Compose
/// has one healthcheck per service that maps cleanly onto
/// liveness semantics ("kill if persistently unhealthy"); a
/// readiness probe would double the per-pod probe traffic for a
/// guess about the user's intent.
fn render_liveness_probe(hc: Option<&ComposeHealthcheck>) -> Option<String> {
    let hc = hc?;
    if hc.disable.unwrap_or(false) {
        return None;
    }
    let argv = parse_healthcheck_test(hc.test.as_ref())?;
    if argv.is_empty() {
        return None;
    }

    let mut s = String::new();
    s.push_str("          livenessProbe:\n");
    s.push_str("            exec:\n");
    s.push_str("              command:\n");
    for token in &argv {
        s.push_str(&format!("                - {}\n", yaml_quote(token)));
    }
    if let Some(secs) = hc.interval.as_deref().and_then(parse_compose_duration_secs) {
        s.push_str(&format!("            periodSeconds: {secs}\n"));
    }
    if let Some(secs) = hc.timeout.as_deref().and_then(parse_compose_duration_secs) {
        s.push_str(&format!("            timeoutSeconds: {secs}\n"));
    }
    if let Some(n) = hc.retries {
        s.push_str(&format!("            failureThreshold: {n}\n"));
    }
    if let Some(secs) = hc
        .start_period
        .as_deref()
        .and_then(parse_compose_duration_secs)
    {
        s.push_str(&format!("            initialDelaySeconds: {secs}\n"));
    }
    Some(s)
}

/// Parse Compose's `healthcheck.test` field into an argv vector
/// ready for K8s `exec.command`. Returns `None` for the explicit
/// "no healthcheck" sentinel (`["NONE"]`) and for shapes we don't
/// recognise. Otherwise:
///
///  * `"curl foo"` → `["sh", "-c", "curl foo"]` (CMD-SHELL fallback)
///  * `["CMD", "curl", "foo"]` → `["curl", "foo"]`
///  * `["CMD-SHELL", "curl foo"]` → `["sh", "-c", "curl foo"]`
///  * `["NONE"]` → `None`
fn parse_healthcheck_test(value: Option<&serde_yml::Value>) -> Option<Vec<String>> {
    let v = value?;
    match v {
        serde_yml::Value::String(s) => {
            // Bare-string form is implicitly CMD-SHELL.
            let trimmed = s.trim();
            if trimmed.is_empty() {
                return None;
            }
            Some(vec!["sh".to_string(), "-c".to_string(), trimmed.to_string()])
        }
        serde_yml::Value::Sequence(items) => {
            let strs: Vec<String> = items
                .iter()
                .filter_map(|i| i.as_str().map(|s| s.to_string()))
                .collect();
            if strs.is_empty() {
                return None;
            }
            match strs[0].as_str() {
                "NONE" => None,
                "CMD" => Some(strs.into_iter().skip(1).collect()),
                "CMD-SHELL" => {
                    // Spec says exactly one shell-string follows.
                    let script = strs.into_iter().nth(1).unwrap_or_default();
                    if script.is_empty() {
                        None
                    } else {
                        Some(vec!["sh".to_string(), "-c".to_string(), script])
                    }
                }
                // No `CMD` / `CMD-SHELL` prefix → treat the whole
                // array as the argv (defensive — some users write
                // shorter forms).
                _ => Some(strs),
            }
        }
        _ => None,
    }
}

/// Parse a Compose duration like `"30s"`, `"1m30s"`, `"2h"` into
/// seconds, rounded down. Returns `None` for unparseable input
/// (we'd rather omit the field than emit nonsense). Sub-second
/// suffixes (`ms`, `us`, `ns`) are clamped to a 1-second floor —
/// K8s probe knobs are integer-second.
fn parse_compose_duration_secs(s: &str) -> Option<u64> {
    let t = s.trim();
    if t.is_empty() {
        return None;
    }
    // Bare integer = seconds (Compose accepts plain numbers as ns
    // strictly, but in practice users write `30` meaning seconds.
    // We bias towards user-friendly behaviour.)
    if let Ok(n) = t.parse::<u64>() {
        return Some(n);
    }

    // Walk char-by-char accumulating a (number, unit) pair stream.
    let mut total: u64 = 0;
    let mut acc: u64 = 0;
    let mut got_digit = false;
    let mut chars = t.chars().peekable();
    while let Some(&c) = chars.peek() {
        if c.is_ascii_digit() {
            acc = acc.saturating_mul(10).saturating_add((c as u64) - 48);
            got_digit = true;
            chars.next();
            continue;
        }
        // Read a unit (1 or 2 letter).
        let mut unit = String::new();
        while let Some(&u) = chars.peek() {
            if u.is_ascii_alphabetic() {
                unit.push(u);
                chars.next();
            } else {
                break;
            }
        }
        let mult: u64 = match unit.as_str() {
            "h" => 3600,
            "m" => 60,
            "s" => 1,
            // Sub-second units floor to 1s — probes don't go
            // finer than seconds at the K8s API level.
            "ms" | "us" | "µs" | "ns" => 0, // accumulate as zero, will floor below
            _ => return None,
        };
        if mult == 0 && acc > 0 {
            // Sub-second component — bump total by 1 if it's the
            // ONLY component, otherwise just discard it.
            if total == 0 && chars.peek().is_none() {
                return Some(1);
            }
        } else {
            total = total.saturating_add(acc.saturating_mul(mult));
        }
        acc = 0;
    }
    if !got_digit {
        return None;
    }
    if total == 0 {
        // Pure-number input was handled above; reaching here means
        // the input was something like "0s" — keep as 0.
        Some(0)
    } else {
        Some(total)
    }
}

/// One service-level secret/config reference resolved to a Pod
/// volume + volumeMount. We carry the mount kind so the volume
/// emit code knows whether to write `secret:` or `configMap:`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MountRefKind {
    Secret,
    Config,
}

#[derive(Debug, Clone)]
struct MountRef {
    /// Top-level key — used as both the K8s resource name and
    /// the in-Pod volume name (sanitised on the way to the
    /// volume name).
    id: String,
    /// Mount path inside the container. Defaults to
    /// `/run/secrets/<id>` for secrets and `/<id>` for configs
    /// when the long-form `target:` is absent.
    target: String,
    kind: MountRefKind,
}

impl MountRef {
    fn volume_name(&self) -> String {
        // Same DNS-label sanitiser as bind mounts — `secret-foo`
        // / `config-foo` prefix avoids collisions when a secret
        // and config share a name.
        let prefix = match self.kind {
            MountRefKind::Secret => "secret",
            MountRefKind::Config => "config",
        };
        bind_mount_configmap_name(prefix, &self.id)
    }
    fn mount_path(&self) -> &str {
        &self.target
    }
}

fn parse_mount_refs(
    items: &[serde_yml::Value],
    kind: MountRefKind,
    top_level: &BTreeMap<String, serde_yml::Value>,
) -> Vec<MountRef> {
    let mut out = Vec::new();
    for v in items {
        match v {
            serde_yml::Value::String(name) => {
                if !top_level.contains_key(name) {
                    // Reference to an undeclared secret/config —
                    // skip silently; emit-time validation in
                    // kubectl will tell the user.
                    continue;
                }
                out.push(MountRef {
                    id: name.clone(),
                    target: default_target(name, kind),
                    kind,
                });
            }
            serde_yml::Value::Mapping(m) => {
                let source = m
                    .get(serde_yml::Value::String("source".into()))
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string());
                let target = m
                    .get(serde_yml::Value::String("target".into()))
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string());
                let Some(id) = source else { continue };
                if !top_level.contains_key(&id) {
                    continue;
                }
                let target = target.unwrap_or_else(|| default_target(&id, kind));
                out.push(MountRef {
                    id,
                    target,
                    kind,
                });
            }
            _ => {}
        }
    }
    out
}

fn default_target(id: &str, kind: MountRefKind) -> String {
    match kind {
        // Compose's documented default for service-level secrets.
        MountRefKind::Secret => format!("/run/secrets/{id}"),
        // Compose mounts top-level configs at `/<id>` by default.
        MountRefKind::Config => format!("/{id}"),
    }
}

/// Emit a `Secret` placeholder for a top-level Compose `secrets:`
/// declaration. We honour the `file:` form by referencing the
/// expected path in a placeholder comment; `external:` and
/// `environment:` forms get a NOTE because both require cluster-
/// side wiring before apply.
fn render_secret_stub(
    name: &str,
    body: &serde_yml::Value,
    namespace: Option<&str>,
) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    let (note, hint) = mount_stub_hints(body);
    let mut s = String::new();
    s.push_str("apiVersion: v1\n");
    s.push_str("kind: Secret\n");
    s.push_str("metadata:\n");
    s.push_str(&ns_line);
    s.push_str(&format!("  name: {name}\n"));
    s.push_str("type: Opaque\n");
    s.push_str("stringData:\n");
    s.push_str("  README.md: |\n");
    s.push_str("    Placeholder Secret generated by Pier-X.\n");
    if let Some(h) = hint {
        s.push_str(&format!("    {h}\n"));
    }
    s.push_str(
        "    Replace this entry with the real key/value pairs, e.g.:\n\
         \x20\x20\x20\x20\x20\x20kubectl create secret generic ",
    );
    s.push_str(name);
    s.push_str(" --from-literal=KEY=value --dry-run=client -o yaml | kubectl apply -f -\n");
    if let Some(n) = note {
        s.push_str(&format!("# NOTE: {n}\n"));
    }
    s
}

/// Emit a `ConfigMap` placeholder for a top-level Compose
/// `configs:` declaration. Same shape as [`render_secret_stub`]
/// but no `type:` field.
fn render_top_level_configmap(
    name: &str,
    body: &serde_yml::Value,
    namespace: Option<&str>,
) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    let (note, hint) = mount_stub_hints(body);
    let mut s = String::new();
    s.push_str("apiVersion: v1\n");
    s.push_str("kind: ConfigMap\n");
    s.push_str("metadata:\n");
    s.push_str(&ns_line);
    s.push_str(&format!("  name: {name}\n"));
    s.push_str("data:\n");
    s.push_str("  README.md: |\n");
    s.push_str("    Placeholder ConfigMap generated by Pier-X.\n");
    if let Some(h) = hint {
        s.push_str(&format!("    {h}\n"));
    }
    s.push_str(
        "    Replace this entry with the real key/value pairs, e.g.:\n\
         \x20\x20\x20\x20\x20\x20kubectl create configmap ",
    );
    s.push_str(name);
    s.push_str(" --from-file=./your-dir/ --dry-run=client -o yaml | kubectl apply -f -\n");
    if let Some(n) = note {
        s.push_str(&format!("# NOTE: {n}\n"));
    }
    s
}

/// Inspect a Compose `secrets:` / `configs:` entry body for
/// `file:` / `external:` / `environment:` shapes. Returns
/// `(top-level NOTE, in-data hint)`. Either may be `None` when
/// the entry is empty / unknown.
fn mount_stub_hints(body: &serde_yml::Value) -> (Option<String>, Option<String>) {
    let serde_yml::Value::Mapping(m) = body else {
        return (None, None);
    };
    if let Some(file) = m
        .get(serde_yml::Value::String("file".into()))
        .and_then(|v| v.as_str())
    {
        return (
            None,
            Some(format!("Compose source file: {file}")),
        );
    }
    if m.get(serde_yml::Value::String("external".into()))
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
    {
        return (
            Some(
                "Compose `external: true` — reference an existing cluster resource"
                    .to_string(),
            ),
            Some(
                "External resource — make sure it already exists in the cluster.".to_string(),
            ),
        );
    }
    if let Some(env) = m
        .get(serde_yml::Value::String("environment".into()))
        .and_then(|v| v.as_str())
    {
        return (
            Some(format!(
                "Compose `environment: {env}` — sourced from env at compose-up time"
            )),
            Some(format!("Source env var on the build host: {env}")),
        );
    }
    (None, None)
}

/// Pull the membership list out of a service's `networks:`
/// field. Compose accepts both a sequence of names and a mapping
/// keyed by name (with optional aliases / ipv4_address / etc. as
/// the value); we only want the names. Filtered to networks that
/// are also declared at the top level — referencing a network
/// that doesn't exist is a Compose-side error and we don't want
/// to mint K8s labels for it.
fn parse_service_networks(
    value: &Option<serde_yml::Value>,
    top_level: &BTreeMap<String, serde_yml::Value>,
) -> Vec<String> {
    let Some(v) = value else { return Vec::new() };
    let mut names: Vec<String> = match v {
        serde_yml::Value::Sequence(seq) => seq
            .iter()
            .filter_map(|i| i.as_str().map(|s| s.to_string()))
            .collect(),
        serde_yml::Value::Mapping(m) => m
            .iter()
            .filter_map(|(k, _)| k.as_str().map(|s| s.to_string()))
            .collect(),
        _ => Vec::new(),
    };
    names.retain(|n| top_level.contains_key(n));
    // Stable order: alphabetical so two services on the same set
    // of networks render their labels in the same order.
    names.sort();
    names.dedup();
    names
}

/// Emit a placeholder `NetworkPolicy` for a top-level
/// `networks:` entry. The policy:
///
///   * selects pods labelled `pier-x.network/<name>: "in"`,
///   * declares Ingress only,
///   * allows ingress from any pod with the same label.
///
/// This is the closest shape to "Compose network = pods can talk
/// to each other" that NetworkPolicy can express. The trailing
/// NOTE warns the user that NetworkPolicy is namespace-scoped
/// default-allow unless their CNI says otherwise — applying this
/// alone won't isolate the pod from outside traffic.
fn render_network_policy(name: &str, namespace: Option<&str>) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    format!(
        "apiVersion: networking.k8s.io/v1\n\
         kind: NetworkPolicy\n\
         metadata:\n\
         {ns}\
         \x20\x20name: pier-x-net-{name}\n\
         spec:\n\
         \x20\x20podSelector:\n\
         \x20\x20\x20\x20matchLabels:\n\
         \x20\x20\x20\x20\x20\x20pier-x.network/{name}: \"in\"\n\
         \x20\x20policyTypes:\n\
         \x20\x20\x20\x20- Ingress\n\
         \x20\x20ingress:\n\
         \x20\x20\x20\x20- from:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20- podSelector:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20matchLabels:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20pier-x.network/{name}: \"in\"\n\
         # NOTE: NetworkPolicy is enforced by the CNI plugin (Calico,\n\
         #       Cilium, etc.). Without one configured, this policy is\n\
         #       a no-op. Add a default-deny policy for the namespace\n\
         #       if you actually want isolation.\n",
        ns = ns_line,
        name = name,
    )
}

fn render_configmap_stub(stub: &ConfigMapStub, namespace: Option<&str>) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    // Inline placeholder content uses YAML's `|` block scalar so
    // the multi-line message survives unchanged. The README-style
    // body tells the operator exactly how to replace it without
    // having to consult docs.
    format!(
        "apiVersion: v1\n\
         kind: ConfigMap\n\
         metadata:\n\
         {ns_line}\
         \x20\x20name: {name}\n\
         data:\n\
         \x20\x20README.md: |\n\
         \x20\x20\x20\x20Placeholder ConfigMap generated by Pier-X.\n\
         \x20\x20\x20\x20Original Compose bind mount: {source} -> {mount_path}\n\
         \x20\x20\x20\x20Replace this entry with the actual files via, e.g.:\n\
         \x20\x20\x20\x20\x20\x20kubectl create configmap {name} --from-file=./your-dir/ --dry-run=client -o yaml | kubectl apply -f -\n",
        ns_line = ns_line,
        name = stub.name,
        source = stub.source,
        mount_path = stub.mount_path,
    )
}

fn render_service(name: &str, svc: &ComposeService, namespace: Option<&str>) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    let ports = parse_ports(&svc.ports);
    let mut s = String::new();
    s.push_str("apiVersion: v1\n");
    s.push_str("kind: Service\n");
    s.push_str("metadata:\n");
    s.push_str(&ns_line);
    s.push_str(&format!("  name: {name}\n"));
    s.push_str("spec:\n");
    s.push_str("  type: ClusterIP\n");
    s.push_str("  selector:\n");
    s.push_str(&format!("    app: {name}\n"));
    s.push_str("  ports:\n");
    for p in &ports {
        s.push_str(&format!("    - name: tcp-{}\n", p.container));
        s.push_str(&format!("      port: {}\n", p.container));
        s.push_str(&format!("      targetPort: {}\n", p.container));
        s.push_str("      protocol: TCP\n");
    }
    s
}

/// Render a single `networking.k8s.io/v1` Ingress resource that
/// routes the configured host to every HTTP-like service in
/// `routes`. Each route becomes one `paths:` entry under the same
/// host rule:
///
/// ```yaml
/// - host: <ingress.host>
///   http:
///     paths:
///       - path: /<service>
///         pathType: Prefix
///         backend:
///           service:
///             name: <service>
///             port:
///               number: <port>
/// ```
///
/// When `ingress.tls_secret` is set, a `tls:` block matching the
/// same host is emitted. Most clusters also require
/// `ingressClassName` — passed through verbatim when set.
fn render_ingress(
    routes: &[(String, u16)],
    namespace: Option<&str>,
    ingress: &IngressOptions,
) -> String {
    let ns_line = match namespace {
        Some(n) => format!("  namespace: {n}\n"),
        None => String::new(),
    };
    let mut s = String::new();
    s.push_str("apiVersion: networking.k8s.io/v1\n");
    s.push_str("kind: Ingress\n");
    s.push_str("metadata:\n");
    s.push_str(&ns_line);
    s.push_str("  name: pier-x-stack\n");
    s.push_str("spec:\n");
    if !ingress.ingress_class.trim().is_empty() {
        s.push_str(&format!(
            "  ingressClassName: {}\n",
            ingress.ingress_class.trim()
        ));
    }
    if !ingress.tls_secret.trim().is_empty() {
        s.push_str("  tls:\n");
        s.push_str("    - hosts:\n");
        s.push_str(&format!("        - {}\n", ingress.host.trim()));
        s.push_str(&format!(
            "      secretName: {}\n",
            ingress.tls_secret.trim()
        ));
    }
    s.push_str("  rules:\n");
    s.push_str(&format!("    - host: {}\n", ingress.host.trim()));
    s.push_str("      http:\n");
    s.push_str("        paths:\n");
    for (svc, port) in routes {
        s.push_str(&format!("          - path: /{}\n", svc));
        s.push_str("            pathType: Prefix\n");
        s.push_str("            backend:\n");
        s.push_str("              service:\n");
        s.push_str(&format!("                name: {}\n", svc));
        s.push_str("                port:\n");
        s.push_str(&format!("                  number: {}\n", port));
    }
    if routes.len() > 1 {
        s.push_str(
            "      # NOTE: each path-prefix routes traffic to a different service.\n\
             \x20\x20\x20\x20\x20\x20#       Most apps need their root URL configured to match\n\
             \x20\x20\x20\x20\x20\x20#       (e.g. Grafana's GF_SERVER_ROOT_URL) — adjust before\n\
             \x20\x20\x20\x20\x20\x20#       applying.\n",
        );
    }
    s
}

/// Pick the first port from `svc` that smells like an HTTP service.
/// Used to decide whether a service is Ingress-eligible — non-HTTP
/// services (Postgres on 5432, Redis on 6379) get skipped so the
/// generated Ingress only covers things a browser can hit.
fn first_http_port(svc: &ComposeService) -> Option<u16> {
    const HTTP_PORTS: &[u16] = &[
        80, 443, 3000, 4000, 5000, 5601, 8000, 8008, 8080, 8081, 8443, 8888,
        9000, 9090, 9091, 9100,
    ];
    parse_ports(&svc.ports)
        .into_iter()
        .map(|p| p.container)
        .find(|p| HTTP_PORTS.contains(p))
}

// ── Helpers ─────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct ParsedPort {
    /// Container-side port. Host port is intentionally ignored
    /// because Services don't carry one — see module docs.
    container: u16,
}

fn has_published_ports(svc: &ComposeService) -> bool {
    !parse_ports(&svc.ports).is_empty()
}

/// Compose port specs come in three shapes:
///   - short `"5432:5432"` / `"5432"`
///   - long  `{ target: 5432, published: 5432, protocol: tcp }`
///   - just an integer `5432`
fn parse_ports(values: &[serde_yml::Value]) -> Vec<ParsedPort> {
    let mut out = Vec::new();
    for v in values {
        match v {
            serde_yml::Value::String(s) => {
                if let Some(p) = parse_port_string(s) {
                    out.push(p);
                }
            }
            serde_yml::Value::Number(n) => {
                if let Some(c) = n.as_u64().and_then(|n| u16::try_from(n).ok()) {
                    out.push(ParsedPort { container: c });
                }
            }
            serde_yml::Value::Mapping(m) => {
                let target = m
                    .get(serde_yml::Value::String("target".into()))
                    .and_then(|v| v.as_u64())
                    .and_then(|n| u16::try_from(n).ok());
                if let Some(c) = target {
                    out.push(ParsedPort { container: c });
                }
            }
            _ => {}
        }
    }
    out
}

fn parse_port_string(s: &str) -> Option<ParsedPort> {
    // Compose accepts `host:container`, `ip:host:container`,
    // `host:container/proto`, `container/proto`, plain `container`.
    let s = s.trim().trim_matches('"');
    let no_proto = s.split('/').next().unwrap_or(s);
    let parts: Vec<&str> = no_proto.split(':').collect();
    let container_str = parts.last().copied().unwrap_or("");
    container_str
        .trim()
        .parse::<u16>()
        .ok()
        .map(|container| ParsedPort { container })
}

#[derive(Debug, Clone)]
struct NamedMount {
    volume: String,
    mount_path: String,
    read_only: bool,
}

#[derive(Debug, Clone)]
struct BindMount {
    /// Raw Compose source token, including the `./` prefix when
    /// present. Used as a hint in the generated ConfigMap's
    /// placeholder content.
    source: String,
    mount_path: String,
    read_only: bool,
}

#[derive(Debug, Clone, Default)]
struct ParsedVolumes {
    named_mounts: Vec<NamedMount>,
    /// Bind mounts split out from the warnings stream so callers
    /// that opted in to ConfigMap lifting can convert them while
    /// other unsupported volume shapes still surface as warnings.
    bind_mounts: Vec<BindMount>,
    /// Unsupported-volume strings (long-form, malformed, etc.).
    warnings: Vec<String>,
}

fn parse_volumes(values: &[serde_yml::Value]) -> ParsedVolumes {
    let mut out = ParsedVolumes::default();
    for v in values {
        // Long-form: `{ type, source, target, read_only }` — when
        // we can extract the four canonical fields the long form
        // is no harder to translate than the short form. Falls
        // through to the legacy "shaped string" path otherwise.
        if let serde_yml::Value::Mapping(m) = v {
            if let Some(parsed) = parse_long_form_volume(m) {
                push_parsed_long_form(&mut out, parsed);
                continue;
            }
            // Mapping that didn't have the canonical fields —
            // surface it so the user knows we punted instead of
            // silently dropping.
            out.warnings.push("long-form volume (unrecognised shape)".to_string());
            continue;
        }
        let raw = match v {
            serde_yml::Value::String(s) => s.clone(),
            _ => {
                out.warnings.push("non-string volume entry".to_string());
                continue;
            }
        };
        // Strip optional `:ro` / `:rw` suffix.
        let (body, ro) = match raw.rsplit_once(':') {
            Some((head, tail)) if tail == "ro" => (head.to_string(), true),
            Some((head, tail)) if tail == "rw" => (head.to_string(), false),
            _ => (raw.clone(), false),
        };
        // Compose volume short form: `<source>:<target>`. The source
        // can be either a named volume (single token, no slashes) or
        // a host path (contains `/` or `.`).
        let parts: Vec<&str> = body.splitn(2, ':').collect();
        if parts.len() != 2 {
            out.warnings.push(raw);
            continue;
        }
        let source = parts[0].trim();
        let target = parts[1].trim();
        let is_path = source.contains('/')
            || source.starts_with('.')
            || source.starts_with('~');
        if is_path {
            // Anonymise the source path enough to keep ConfigMap
            // generation possible: callers see the verbatim source
            // string and decide whether to lift or warn.
            out.bind_mounts.push(BindMount {
                source: source.to_string(),
                mount_path: target.to_string(),
                read_only: ro,
            });
            // Keep a parallel warning so the legacy "drop with note"
            // path keeps working when `lift_bind_mounts` is off.
            out.warnings.push(raw);
            continue;
        }
        out.named_mounts.push(NamedMount {
            volume: source.to_string(),
            mount_path: target.to_string(),
            read_only: ro,
        });
    }
    out
}

/// Decoded long-form volume — exactly one of the two variants
/// per entry. Kept private to this module; the caller routes
/// each variant into the existing `ParsedVolumes` buckets so the
/// rest of the renderer stays untouched.
enum ParsedLongFormVolume {
    Named { volume: String, mount_path: String, read_only: bool },
    Bind { source: String, mount_path: String, read_only: bool },
    /// Long form with `type:` we don't translate (`tmpfs` /
    /// `npipe` / `cluster`). We surface a warning string the
    /// caller pushes onto `ParsedVolumes.warnings`.
    Unsupported(String),
}

/// Long-form volume parser. Returns `None` if the mapping is
/// missing the canonical `target:` field (without it we can't
/// place anything inside the container and there's nothing useful
/// to do). The `type:` field defaults to `"volume"` per the
/// Compose spec; `read_only:` defaults to false.
fn parse_long_form_volume(m: &serde_yml::Mapping) -> Option<ParsedLongFormVolume> {
    let target = m
        .get(serde_yml::Value::String("target".into()))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())?;
    let kind = m
        .get(serde_yml::Value::String("type".into()))
        .and_then(|v| v.as_str())
        .unwrap_or("volume")
        .to_string();
    let source = m
        .get(serde_yml::Value::String("source".into()))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_default();
    let read_only = m
        .get(serde_yml::Value::String("read_only".into()))
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    Some(match kind.as_str() {
        "volume" => {
            // `source:` for named volumes is the volume name;
            // when missing the volume is anonymous (we still
            // need a name to mount it, so we synthesise one
            // from the target path so the manifest applies).
            let volume = if source.is_empty() {
                bind_mount_configmap_name("vol", &target)
            } else {
                source
            };
            ParsedLongFormVolume::Named {
                volume,
                mount_path: target,
                read_only,
            }
        }
        "bind" => ParsedLongFormVolume::Bind {
            source: if source.is_empty() {
                ".".to_string()
            } else {
                source
            },
            mount_path: target,
            read_only,
        },
        other => ParsedLongFormVolume::Unsupported(format!(
            "long-form volume type '{other}' not translated"
        )),
    })
}

fn push_parsed_long_form(out: &mut ParsedVolumes, parsed: ParsedLongFormVolume) {
    match parsed {
        ParsedLongFormVolume::Named {
            volume,
            mount_path,
            read_only,
        } => out.named_mounts.push(NamedMount {
            volume,
            mount_path,
            read_only,
        }),
        ParsedLongFormVolume::Bind {
            source,
            mount_path,
            read_only,
        } => {
            out.bind_mounts.push(BindMount {
                source: source.clone(),
                mount_path: mount_path.clone(),
                read_only,
            });
            // Same parallel warning as the short-form bind mount
            // so the legacy `lift_bind_mounts: false` path keeps
            // surfacing the # NOTE about hostPath / ConfigMap.
            out.warnings.push(format!(
                "{}:{}{}",
                source,
                mount_path,
                if read_only { ":ro" } else { "" }
            ));
        }
        ParsedLongFormVolume::Unsupported(msg) => {
            out.warnings.push(msg);
        }
    }
}

fn parse_environment(value: &Option<serde_yml::Value>) -> Vec<(String, String)> {
    let Some(v) = value else { return Vec::new() };
    match v {
        serde_yml::Value::Mapping(m) => m
            .iter()
            .filter_map(|(k, v)| {
                let key = k.as_str()?.to_string();
                let val = match v {
                    serde_yml::Value::String(s) => s.clone(),
                    serde_yml::Value::Number(n) => n.to_string(),
                    serde_yml::Value::Bool(b) => b.to_string(),
                    _ => return None,
                };
                Some((key, val))
            })
            .collect(),
        serde_yml::Value::Sequence(items) => items
            .iter()
            .filter_map(|item| item.as_str())
            .filter_map(|s| {
                let (k, v) = s.split_once('=')?;
                Some((k.trim().to_string(), v.trim().to_string()))
            })
            .collect(),
        _ => Vec::new(),
    }
}

fn command_to_array(value: &serde_yml::Value) -> Vec<String> {
    match value {
        serde_yml::Value::String(s) => {
            // Conservative split — handles the redis template's
            // `redis-server --appendonly yes` style. For anything
            // with quoting / globbing we'd need a real shell parser;
            // none of the built-in templates need that.
            s.split_whitespace().map(|x| x.to_string()).collect()
        }
        serde_yml::Value::Sequence(items) => items
            .iter()
            .filter_map(|i| i.as_str().map(|s| s.to_string()))
            .collect(),
        _ => Vec::new(),
    }
}

/// YAML scalar quoting — wraps the value in double quotes when it
/// would otherwise be parsed as a non-string by a strict YAML
/// reader (numbers, booleans, leading whitespace, special chars).
/// We err on the side of quoting: the output is for humans to apply
/// with `kubectl`, not for golf scoring.
fn yaml_quote(s: &str) -> String {
    let needs_quote = s.is_empty()
        || s.chars().any(|c| matches!(c, ':' | '#' | '"' | '\'' | '\n' | '{' | '}' | '[' | ']' | ',' | '&' | '*' | '|' | '>' | '!' | '%' | '@' | '`'))
        || s.parse::<f64>().is_ok()
        || matches!(s.to_lowercase().as_str(), "true" | "false" | "yes" | "no" | "on" | "off" | "null" | "~");
    if needs_quote {
        format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        s.to_string()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
/// Echo of a converted template — used by the Tauri command return
/// type so the frontend can preview both the source and target side
/// by side without re-fetching.
pub struct ComposeK8sExport {
    /// The original Compose YAML (verbatim from the registry).
    pub compose_yaml: String,
    /// The generated multi-document Kubernetes manifest.
    pub k8s_yaml: String,
    /// Number of Deployments produced.
    pub deployment_count: usize,
    /// Number of Services produced.
    pub service_count: usize,
    /// Number of PersistentVolumeClaims produced.
    pub pvc_count: usize,
    /// Number of Ingress resources produced (0 or 1 — the
    /// converter emits at most one combined Ingress).
    pub ingress_count: usize,
    /// Number of ConfigMap resources produced. Includes both
    /// stubs lifted from bind mounts (when
    /// `IngressOptions.lift_bind_mounts` is on) AND ConfigMaps
    /// emitted from top-level Compose `configs:` declarations.
    pub configmap_count: usize,
    /// Number of `Secret` resources emitted from top-level
    /// Compose `secrets:` declarations.
    pub secret_count: usize,
    /// Number of `NetworkPolicy` resources emitted from
    /// top-level Compose `networks:` declarations.
    pub networkpolicy_count: usize,
    /// Lines flagged for manual attention (bind mounts dropped,
    /// `depends_on` etc).
    pub warnings: Vec<String>,
}

/// Higher-level helper used by the Tauri command. Counts the
/// emitted resources by re-parsing the output (cheap — a few KB)
/// so the dialog can summarise "X Deployments, Y Services, Z PVCs"
/// without the frontend having to count `---` separators itself.
pub fn convert_with_summary(
    compose_yaml: &str,
    namespace: Option<&str>,
) -> Result<ComposeK8sExport, String> {
    convert_with_summary_and_options(
        compose_yaml,
        namespace,
        &IngressOptions::default(),
    )
}

/// Variant of [`convert_with_summary`] that lets the caller pass
/// through Ingress options. Used by the Tauri command layer when
/// the panel's "include Ingress" checkbox is on.
pub fn convert_with_summary_and_options(
    compose_yaml: &str,
    namespace: Option<&str>,
    ingress: &IngressOptions,
) -> Result<ComposeK8sExport, String> {
    let k8s_yaml = convert_with_options(compose_yaml, namespace, ingress)?;
    let mut deployment_count = 0;
    let mut service_count = 0;
    let mut pvc_count = 0;
    let mut ingress_count = 0;
    let mut configmap_count = 0;
    let mut secret_count = 0;
    let mut networkpolicy_count = 0;
    let mut warnings = Vec::new();
    for doc in k8s_yaml.split("\n---\n") {
        let kind = doc
            .lines()
            .find(|l| l.starts_with("kind:"))
            .map(|l| l.trim_start_matches("kind:").trim());
        match kind {
            Some("Deployment") => deployment_count += 1,
            Some("Service") => service_count += 1,
            Some("PersistentVolumeClaim") => pvc_count += 1,
            Some("Ingress") => ingress_count += 1,
            Some("ConfigMap") => configmap_count += 1,
            Some("Secret") => secret_count += 1,
            Some("NetworkPolicy") => networkpolicy_count += 1,
            _ => {}
        }
        for l in doc.lines() {
            let trimmed = l.trim_start();
            if trimmed.starts_with("# NOTE:") {
                warnings.push(trimmed.trim_start_matches("# NOTE:").trim().to_string());
            }
        }
        // ConfigMap / Secret etcd size sanity. The Kubernetes object
        // size cap is 1 MiB *post-encoding* (etcd's request size
        // limit). Our placeholders are tiny, but a user who pastes
        // their actual config blob into the YAML before applying can
        // blow past it. Warn early at 80% so they can split before
        // discovering the failure at `kubectl apply` time.
        if matches!(kind, Some("ConfigMap") | Some("Secret")) {
            check_etcd_size_limit(doc, kind.unwrap_or("?"), &mut warnings);
        }
    }
    Ok(ComposeK8sExport {
        compose_yaml: compose_yaml.to_string(),
        k8s_yaml,
        deployment_count,
        service_count,
        pvc_count,
        ingress_count,
        configmap_count,
        secret_count,
        networkpolicy_count,
        warnings,
    })
}

/// Default soft and hard etcd object-size limits, in bytes. The hard
/// limit (1 MiB) is etcd's per-key request cap that Kubernetes
/// inherits for ConfigMap / Secret bodies. The soft limit (80% of
/// hard) gives users a chance to split their data before they hit
/// the cliff at `kubectl apply` time.
const ETCD_HARD_LIMIT_BYTES: usize = 1024 * 1024;
const ETCD_SOFT_LIMIT_BYTES: usize = 800 * 1024;

/// Read the `metadata.name:` field from a rendered manifest doc.
/// Best-effort only — used purely for human-friendly warning text,
/// so missing / malformed names degrade to "?". The renderer
/// always emits `name:` after `metadata:`, so for our own output
/// this lookup is reliable.
fn extract_metadata_name(doc: &str) -> String {
    let mut in_metadata = false;
    for line in doc.lines() {
        let trimmed = line.trim_start();
        if trimmed == "metadata:" {
            in_metadata = true;
            continue;
        }
        if in_metadata {
            if let Some(rest) = trimmed.strip_prefix("name:") {
                return rest.trim().trim_matches('"').to_string();
            }
            // Out of the metadata block once we see a non-indented
            // top-level key; bail.
            if !line.starts_with(' ') && !line.is_empty() {
                break;
            }
        }
    }
    "?".to_string()
}

/// Push a warning when `doc`'s UTF-8 byte size approaches or exceeds
/// the etcd 1 MiB cap. We measure the rendered YAML — base64 padding
/// for Secrets is already accounted for since the body is what gets
/// stored in etcd verbatim.
fn check_etcd_size_limit(doc: &str, kind: &str, warnings: &mut Vec<String>) {
    let bytes = doc.len();
    if bytes < ETCD_SOFT_LIMIT_BYTES {
        return;
    }
    let name = extract_metadata_name(doc);
    let kib = bytes / 1024;
    if bytes >= ETCD_HARD_LIMIT_BYTES {
        warnings.push(format!(
            "{kind}/{name} is {kib} KiB — exceeds the 1 MiB etcd object-size limit. \
             kubectl apply will fail; split this resource into smaller pieces \
             (e.g. one ConfigMap per directory) or move large blobs into a PVC."
        ));
    } else {
        warnings.push(format!(
            "{kind}/{name} is {kib} KiB — approaching the 1 MiB etcd object-size limit. \
             Consider splitting before `kubectl apply` starts rejecting the resource."
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const POSTGRES_YAML: &str = r#"services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: piertest
      POSTGRES_PASSWORD: piertest
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
"#;

    const NGINX_YAML: &str = r#"services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
"#;

    #[test]
    fn converts_postgres_template() {
        let out = convert(POSTGRES_YAML, None).expect("convert");
        assert!(out.contains("kind: Deployment"));
        assert!(out.contains("kind: Service"));
        assert!(out.contains("kind: PersistentVolumeClaim"));
        assert!(out.contains("image: postgres:17"));
        assert!(out.contains("containerPort: 5432"));
        assert!(out.contains("name: pg-data"));
        assert!(out.contains("persistentVolumeClaim:"));
        // POSTGRES_PASSWORD value is "piertest" (no quote needed)
        // but we always emit it through yaml_quote — accept either.
        assert!(out.contains("POSTGRES_PASSWORD"));
    }

    #[test]
    fn drops_bind_mounts_with_warning() {
        let out = convert(NGINX_YAML, None).expect("convert");
        assert!(out.contains("kind: Deployment"));
        // The `./www:/usr/share/nginx/html:ro` mount is a bind
        // mount; should NOT show up as a PVC reference.
        assert!(!out.contains("claimName: ./www"));
        // But the deployment should call out that it was dropped.
        assert!(out.contains("bind mount"));
    }

    #[test]
    fn applies_namespace_when_provided() {
        let out = convert(POSTGRES_YAML, Some("piertest")).expect("convert");
        // Namespace should appear under each metadata block.
        assert!(out.contains("namespace: piertest"));
    }

    #[test]
    fn summary_counts_resources() {
        let summary = convert_with_summary(POSTGRES_YAML, None).expect("convert");
        assert_eq!(summary.deployment_count, 1);
        assert_eq!(summary.service_count, 1);
        assert_eq!(summary.pvc_count, 1);
    }

    #[test]
    fn handles_grafana_two_service_template() {
        let yaml = r#"services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
  grafana:
    image: grafana/grafana:latest
    depends_on: [prometheus]
    ports:
      - "3000:3000"
volumes:
  prom-data:
"#;
        let summary = convert_with_summary(yaml, None).expect("convert");
        assert_eq!(summary.deployment_count, 2);
        assert_eq!(summary.service_count, 2);
        assert_eq!(summary.pvc_count, 1);
        assert!(summary
            .warnings
            .iter()
            .any(|w| w.contains("depends_on")));
    }

    #[test]
    fn handles_array_environment() {
        let yaml = r#"services:
  app:
    image: alpine:3
    environment:
      - FOO=bar
      - BAZ=qux
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("name: FOO"));
        assert!(out.contains("name: BAZ"));
    }

    #[test]
    fn rejects_service_with_no_image() {
        let yaml = r#"services:
  broken:
    ports:
      - "80:80"
"#;
        let err = convert(yaml, None).expect_err("should fail");
        assert!(err.contains("no `image:`"));
    }

    #[test]
    fn empty_compose_yields_empty_output() {
        let out = convert("services: {}\n", None).expect("convert");
        // Only the header banner — no Deployment/Service/PVC.
        assert!(!out.contains("kind: Deployment"));
        assert!(!out.contains("kind: Service"));
    }

    const NGINX_HTTP_YAML: &str = r#"services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
"#;

    const POSTGRES_NON_HTTP_YAML: &str = r#"services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
"#;

    #[test]
    fn ingress_emitted_when_host_set_and_http_port_present() {
        let opts = IngressOptions {
            host: "example.com".to_string(),
            ingress_class: "nginx".to_string(),
            tls_secret: String::new(),
            lift_bind_mounts: false,
        };
        let out = convert_with_options(NGINX_HTTP_YAML, None, &opts).expect("convert");
        assert!(out.contains("kind: Ingress"));
        assert!(out.contains("ingressClassName: nginx"));
        assert!(out.contains("host: example.com"));
        assert!(out.contains("path: /nginx"));
        assert!(out.contains("number: 80"));
    }

    #[test]
    fn ingress_skipped_for_non_http_services() {
        // Postgres on 5432 isn't HTTP — the Ingress doc shouldn't
        // appear even though the host is set.
        let opts = IngressOptions {
            host: "db.example.com".to_string(),
            ingress_class: String::new(),
            tls_secret: String::new(),
            lift_bind_mounts: false,
        };
        let out =
            convert_with_options(POSTGRES_NON_HTTP_YAML, None, &opts).expect("convert");
        assert!(!out.contains("kind: Ingress"));
    }

    #[test]
    fn ingress_tls_block_emitted_when_secret_set() {
        let opts = IngressOptions {
            host: "example.com".to_string(),
            ingress_class: String::new(),
            tls_secret: "example-tls".to_string(),
            lift_bind_mounts: false,
        };
        let out = convert_with_options(NGINX_HTTP_YAML, None, &opts).expect("convert");
        assert!(out.contains("tls:"));
        assert!(out.contains("secretName: example-tls"));
        assert!(out.contains("- example.com"));
    }

    #[test]
    fn ingress_skipped_when_host_empty() {
        let opts = IngressOptions {
            host: String::new(),
            ingress_class: "nginx".to_string(),
            tls_secret: String::new(),
            lift_bind_mounts: false,
        };
        let out = convert_with_options(NGINX_HTTP_YAML, None, &opts).expect("convert");
        assert!(!out.contains("kind: Ingress"));
    }

    #[test]
    fn ingress_summary_count_reflects_emission() {
        let opts = IngressOptions {
            host: "example.com".to_string(),
            ingress_class: "nginx".to_string(),
            tls_secret: String::new(),
            lift_bind_mounts: false,
        };
        let summary =
            convert_with_summary_and_options(NGINX_HTTP_YAML, None, &opts).expect("convert");
        assert_eq!(summary.ingress_count, 1);

        let summary_no_ingress = convert_with_summary(NGINX_HTTP_YAML, None).expect("convert");
        assert_eq!(summary_no_ingress.ingress_count, 0);
    }

    #[test]
    fn lifts_bind_mount_to_configmap_when_opted_in() {
        let opts = IngressOptions {
            host: String::new(),
            ingress_class: String::new(),
            tls_secret: String::new(),
            lift_bind_mounts: true,
        };
        let out = convert_with_options(NGINX_YAML, None, &opts).expect("convert");
        // ConfigMap doc emitted before Deployment.
        assert!(out.contains("kind: ConfigMap"));
        // Volume on the Pod references the ConfigMap, NOT a PVC.
        assert!(out.contains("configMap:"));
        assert!(out.contains("name: nginx-www"));
        // Mount path survived from the original `:/usr/share/nginx/html:ro`.
        assert!(out.contains("mountPath: /usr/share/nginx/html"));
        assert!(out.contains("readOnly: true"));
        // `# NOTE: bind mount '...' was dropped` should NOT appear
        // — we lifted it.
        assert!(!out.contains("was dropped"));
    }

    #[test]
    fn keeps_dropping_bind_mounts_when_opt_off() {
        let opts = IngressOptions {
            host: String::new(),
            ingress_class: String::new(),
            tls_secret: String::new(),
            lift_bind_mounts: false,
        };
        let out = convert_with_options(NGINX_YAML, None, &opts).expect("convert");
        assert!(!out.contains("kind: ConfigMap"));
        assert!(out.contains("was dropped"));
    }

    #[test]
    fn lifted_configmap_count_in_summary() {
        let opts = IngressOptions {
            host: String::new(),
            ingress_class: String::new(),
            tls_secret: String::new(),
            lift_bind_mounts: true,
        };
        let summary =
            convert_with_summary_and_options(NGINX_YAML, None, &opts).expect("convert");
        assert_eq!(summary.configmap_count, 1);
    }

    #[test]
    fn healthcheck_array_cmd_form_translates_to_exec_probe() {
        let yaml = r#"services:
  api:
    image: nginx:alpine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("livenessProbe:"));
        assert!(out.contains("exec:"));
        assert!(out.contains("- curl"));
        assert!(out.contains("- -f"));
        // URLs contain `:` which `yaml_quote` wraps in quotes —
        // accept either bare or quoted form so the assertion
        // doesn't break if quoting heuristics change.
        assert!(
            out.contains("http://localhost/health"),
            "missing url in {out}"
        );
        assert!(out.contains("periodSeconds: 30"));
        assert!(out.contains("timeoutSeconds: 5"));
        assert!(out.contains("failureThreshold: 3"));
        assert!(out.contains("initialDelaySeconds: 10"));
    }

    #[test]
    fn healthcheck_cmd_shell_form_wraps_in_sh() {
        let yaml = r#"services:
  api:
    image: nginx:alpine
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health"]
      interval: 1m
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("- sh"));
        assert!(out.contains("- -c"));
        assert!(out.contains("- \"curl -fsS http://localhost/health\""));
        // 1m → 60 seconds.
        assert!(out.contains("periodSeconds: 60"));
    }

    #[test]
    fn healthcheck_string_form_implicitly_cmd_shell() {
        let yaml = r#"services:
  api:
    image: nginx:alpine
    healthcheck:
      test: "wget --spider http://localhost"
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("- sh"));
        assert!(out.contains("wget --spider http://localhost"));
    }

    #[test]
    fn healthcheck_none_skips_probe() {
        let yaml = r#"services:
  api:
    image: nginx:alpine
    healthcheck:
      test: ["NONE"]
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(!out.contains("livenessProbe:"));
    }

    #[test]
    fn healthcheck_disable_flag_skips_probe() {
        let yaml = r#"services:
  api:
    image: nginx:alpine
    healthcheck:
      disable: true
      test: ["CMD", "curl", "http://localhost"]
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(!out.contains("livenessProbe:"));
    }

    #[test]
    fn duration_parser_handles_compose_styles() {
        assert_eq!(parse_compose_duration_secs("30"), Some(30));
        assert_eq!(parse_compose_duration_secs("30s"), Some(30));
        assert_eq!(parse_compose_duration_secs("1m"), Some(60));
        assert_eq!(parse_compose_duration_secs("1m30s"), Some(90));
        assert_eq!(parse_compose_duration_secs("2h"), Some(7200));
        assert_eq!(parse_compose_duration_secs("0s"), Some(0));
        // Sub-second only → minimum 1 second.
        assert_eq!(parse_compose_duration_secs("500ms"), Some(1));
        // Garbage → None (skip the probe knob rather than guess).
        assert_eq!(parse_compose_duration_secs("forever"), None);
        assert_eq!(parse_compose_duration_secs(""), None);
    }

    #[test]
    fn top_level_secret_with_file_form_emits_stub() {
        let yaml = r#"secrets:
  db_password:
    file: ./db_password.txt
services:
  app:
    image: alpine:3
    secrets:
      - db_password
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("kind: Secret"));
        assert!(out.contains("name: db_password"));
        assert!(out.contains("type: Opaque"));
        // The Pod referencing it should have a `secret:` volume.
        assert!(out.contains("secret:"));
        assert!(out.contains("secretName: db_password"));
        // Default mount path is /run/secrets/<name>.
        assert!(out.contains("mountPath: /run/secrets/db_password"));
        assert!(out.contains("readOnly: true"));
    }

    #[test]
    fn top_level_config_with_file_form_emits_stub() {
        let yaml = r#"configs:
  app_conf:
    file: ./app.conf
services:
  app:
    image: alpine:3
    configs:
      - app_conf
"#;
        let out = convert(yaml, None).expect("convert");
        // Two ConfigMaps shouldn't appear — one is the lifted
        // bind-mount path (off here) and the other is the
        // top-level. Only the top-level fires.
        assert!(out.contains("kind: ConfigMap"));
        assert!(out.contains("name: app_conf"));
        assert!(out.contains("configMap:"));
        // Default mount path is /<name>.
        assert!(out.contains("mountPath: /app_conf"));
    }

    #[test]
    fn long_form_target_overrides_default_mount_path() {
        let yaml = r#"secrets:
  api_key:
    file: ./api.key
services:
  app:
    image: alpine:3
    secrets:
      - source: api_key
        target: /etc/myapp/api.key
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("mountPath: /etc/myapp/api.key"));
        // Default path should NOT appear.
        assert!(!out.contains("/run/secrets/api_key"));
    }

    #[test]
    fn external_secret_emits_note() {
        let yaml = r#"secrets:
  shared:
    external: true
services: {}
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("kind: Secret"));
        // Footer NOTE explains the cluster-side wiring caveat.
        assert!(out.contains("# NOTE:"));
        assert!(out.contains("external"));
    }

    #[test]
    fn unknown_secret_reference_skipped_silently() {
        let yaml = r#"services:
  app:
    image: alpine:3
    secrets:
      - undeclared
"#;
        let out = convert(yaml, None).expect("convert");
        // No top-level `secrets:` block → no Secret resource.
        // The dangling reference is silently skipped (kubectl
        // would report it at apply-time).
        assert!(!out.contains("kind: Secret"));
        assert!(!out.contains("/run/secrets/undeclared"));
    }

    #[test]
    fn summary_counts_secrets_and_configs() {
        let yaml = r#"secrets:
  db_password:
    file: ./pw.txt
configs:
  app_conf:
    file: ./app.conf
services:
  app:
    image: alpine:3
    secrets:
      - db_password
    configs:
      - app_conf
"#;
        let summary = convert_with_summary(yaml, None).expect("convert");
        assert_eq!(summary.secret_count, 1);
        assert_eq!(summary.configmap_count, 1);
    }

    #[test]
    fn deploy_resources_limits_translate_to_k8s_limits() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("resources:"));
        assert!(out.contains("limits:"));
        // yaml_quote wraps numeric-looking values like `0.5` but
        // leaves bare K8s-style memory tokens (`256M`, `512Mi`)
        // alone — accept either form so the test isn't tied to
        // the quoting heuristic.
        assert!(out.contains("cpu: \"0.5\""));
        assert!(out.contains("memory: 256M") || out.contains("memory: \"256M\""));
        assert!(out.contains("requests:"));
        assert!(out.contains("cpu: \"0.25\""));
        assert!(out.contains("memory: 128M") || out.contains("memory: \"128M\""));
    }

    #[test]
    fn deploy_resources_only_limits_omits_requests() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      resources:
        limits:
          memory: 512M
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("resources:"));
        assert!(out.contains("limits:"));
        assert!(!out.contains("requests:"));
    }

    #[test]
    fn deploy_resources_empty_omits_block() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      resources:
        limits: {}
        reservations: {}
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(!out.contains("resources:"));
    }

    #[test]
    fn deploy_resources_numeric_cpus_coerce_to_string() {
        // `cpus: 0.5` (YAML number) — K8s wants a string in
        // resource quantities, so the renderer should coerce.
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      resources:
        limits:
          cpus: 0.5
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("cpu: \"0.5\""));
    }

    #[test]
    fn deploy_restart_policy_overrides_service_level_restart() {
        // `restart: always` → omit (K8s default Always); but
        // `deploy.restart_policy.condition: on-failure` should
        // win and emit `restartPolicy: OnFailure`.
        let yaml = r#"services:
  api:
    image: alpine:3
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("restartPolicy: OnFailure"));
    }

    #[test]
    fn deploy_restart_policy_none_maps_to_never() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      restart_policy:
        condition: none
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("restartPolicy: Never"));
    }

    #[test]
    fn deploy_restart_policy_any_omits_field() {
        // `any` is Compose's default — maps to K8s default
        // `Always`, which we omit to keep manifests tight.
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      restart_policy:
        condition: any
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(!out.contains("restartPolicy:"));
    }

    #[test]
    fn long_form_volume_named_translates_like_short_form() {
        let yaml = r#"services:
  app:
    image: alpine:3
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
        read_only: false
volumes:
  pg-data:
"#;
        let out = convert(yaml, None).expect("convert");
        // Same shape as the short form: PVC + Pod volume +
        // volumeMount.
        assert!(out.contains("kind: PersistentVolumeClaim"));
        assert!(out.contains("name: pg-data"));
        assert!(out.contains("mountPath: /var/lib/postgresql/data"));
        assert!(out.contains("claimName: pg-data"));
    }

    #[test]
    fn long_form_volume_read_only_propagates() {
        let yaml = r#"services:
  app:
    image: alpine:3
    volumes:
      - type: volume
        source: cfg
        target: /etc/app
        read_only: true
volumes:
  cfg:
"#;
        let out = convert(yaml, None).expect("convert");
        // The mount should pick up the `read_only: true` field.
        assert!(out.contains("readOnly: true"));
    }

    #[test]
    fn long_form_volume_bind_routes_to_bind_mount_path() {
        let yaml = r#"services:
  app:
    image: alpine:3
    volumes:
      - type: bind
        source: ./www
        target: /usr/share/nginx/html
        read_only: true
"#;
        let out = convert(yaml, None).expect("convert");
        // Same legacy behaviour as the short form `./www:/foo:ro`.
        assert!(out.contains("# NOTE: bind mount"));
        assert!(out.contains("./www:/usr/share/nginx/html:ro"));
    }

    #[test]
    fn long_form_volume_bind_lifts_to_configmap_when_opted_in() {
        let yaml = r#"services:
  app:
    image: alpine:3
    volumes:
      - type: bind
        source: ./www
        target: /usr/share/nginx/html
"#;
        let opts = IngressOptions {
            host: String::new(),
            ingress_class: String::new(),
            tls_secret: String::new(),
            lift_bind_mounts: true,
        };
        let out = convert_with_options(yaml, None, &opts).expect("convert");
        assert!(out.contains("kind: ConfigMap"));
        assert!(out.contains("mountPath: /usr/share/nginx/html"));
    }

    #[test]
    fn long_form_volume_unsupported_type_warns() {
        let yaml = r#"services:
  app:
    image: alpine:3
    volumes:
      - type: tmpfs
        target: /tmp
"#;
        let out = convert(yaml, None).expect("convert");
        // We can't usefully translate tmpfs; surface a NOTE.
        assert!(out.contains("# NOTE:"));
        assert!(out.contains("tmpfs"));
    }

    #[test]
    fn top_level_network_emits_networkpolicy_and_pod_label() {
        let yaml = r#"networks:
  backend:
services:
  api:
    image: alpine:3
    networks:
      - backend
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("kind: NetworkPolicy"));
        assert!(out.contains("name: pier-x-net-backend"));
        assert!(out.contains("pier-x.network/backend: \"in\""));
        assert!(
            out.matches("pier-x.network/backend: \"in\"").count() >= 3,
            "label should appear in pod template + policy podSelector + ingress from selector"
        );
    }

    #[test]
    fn service_network_membership_filtered_to_declared_only() {
        let yaml = r#"services:
  api:
    image: alpine:3
    networks:
      - phantom
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(!out.contains("kind: NetworkPolicy"));
        assert!(!out.contains("pier-x.network/phantom"));
    }

    #[test]
    fn deploy_replicas_propagates_to_deployment_spec() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      replicas: 3
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("replicas: 3"));
        assert!(!out.contains("replicas: 1"));
    }

    #[test]
    fn deploy_replicas_zero_falls_back_to_default() {
        let yaml = r#"services:
  api:
    image: alpine:3
    deploy:
      replicas: 0
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("replicas: 1"));
    }

    #[test]
    fn networkpolicy_count_in_summary() {
        let yaml = r#"networks:
  frontend:
  backend:
services:
  app:
    image: alpine:3
    networks:
      - frontend
      - backend
"#;
        let summary = convert_with_summary(yaml, None).expect("convert");
        assert_eq!(summary.networkpolicy_count, 2);
    }

    #[test]
    fn network_membership_via_mapping_form_works() {
        let yaml = r#"networks:
  backend:
services:
  app:
    image: alpine:3
    networks:
      backend: {}
"#;
        let out = convert(yaml, None).expect("convert");
        assert!(out.contains("pier-x.network/backend: \"in\""));
    }

    #[test]
    fn bind_mount_configmap_name_sanitises() {
        // Various weird inputs → kubernetes-safe name.
        assert_eq!(bind_mount_configmap_name("nginx", "./www"), "nginx-www");
        assert_eq!(
            bind_mount_configmap_name("svc", "/etc/foo/bar"),
            "svc-etc-foo-bar"
        );
        assert_eq!(
            bind_mount_configmap_name("svc", "./Some_DIR"),
            "svc-some-dir"
        );
        // Trailing/leading separators and slashes shouldn't produce
        // dashes at the boundary.
        let n = bind_mount_configmap_name("svc", "./www/");
        assert!(!n.starts_with('-'));
        assert!(!n.ends_with('-'));
    }

    #[test]
    fn etcd_size_check_silent_on_small_configmap() {
        // Build a minimal ConfigMap doc — the size check should not
        // fire at all because we're well under the 800 KiB threshold.
        let doc = "apiVersion: v1\n\
                   kind: ConfigMap\n\
                   metadata:\n  name: small-cm\n\
                   data:\n  hello: world\n";
        let mut warnings: Vec<String> = Vec::new();
        check_etcd_size_limit(doc, "ConfigMap", &mut warnings);
        assert!(warnings.is_empty(), "small ConfigMap should not warn");
    }

    #[test]
    fn etcd_size_check_warns_at_soft_limit() {
        // Pad a ConfigMap body with 850 KiB of filler to land between
        // the soft (800 KiB) and hard (1 MiB) thresholds.
        let filler = "x".repeat(850 * 1024);
        let doc = format!(
            "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: chunky\ndata:\n  blob: |\n    {filler}\n"
        );
        let mut warnings: Vec<String> = Vec::new();
        check_etcd_size_limit(&doc, "ConfigMap", &mut warnings);
        assert_eq!(warnings.len(), 1, "soft-limit ConfigMap should warn once");
        assert!(
            warnings[0].contains("approaching"),
            "soft warning should mention approaching the limit, got: {}",
            warnings[0]
        );
        assert!(
            warnings[0].contains("chunky"),
            "warning should mention the object name, got: {}",
            warnings[0]
        );
    }

    #[test]
    fn etcd_size_check_warns_at_hard_limit() {
        // 1.1 MiB filler pushes past the etcd cap entirely.
        let filler = "y".repeat(1100 * 1024);
        let doc = format!(
            "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: huge\ndata:\n  blob: |\n    {filler}\n"
        );
        let mut warnings: Vec<String> = Vec::new();
        check_etcd_size_limit(&doc, "ConfigMap", &mut warnings);
        assert_eq!(warnings.len(), 1);
        assert!(
            warnings[0].contains("exceeds"),
            "hard warning should mention exceeding the limit, got: {}",
            warnings[0]
        );
        assert!(
            warnings[0].contains("kubectl apply will fail"),
            "hard warning should call out the apply failure, got: {}",
            warnings[0]
        );
    }

    #[test]
    fn extract_metadata_name_handles_quoted_name() {
        let doc = "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: \"my-cm\"\ndata: {}\n";
        assert_eq!(extract_metadata_name(doc), "my-cm");
    }

    #[test]
    fn extract_metadata_name_returns_question_when_missing() {
        let doc = "apiVersion: v1\nkind: ConfigMap\ndata: {}\n";
        assert_eq!(extract_metadata_name(doc), "?");
    }
}
